### ISSUE TITLE
Events - My Community - crash

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#1017]
**Describe the bug**
With the recent PROD deployment "Events - My Communities" is broken.

As a community admin, it gives a white screen, and the following javascript console:

![Screenshot 2023-06-21 at 12 39 25 PM](https://github.com/massenergize/frontend-admin/assets/12800484/90da01d4-f682-46f6-a840-7572d3d0bc84)

**Comment by abdullai-t** [comment]
@BradHN1, This bug is fixed already. Dev and canary work just fine.

**Comment by BradHN1** [comment]
Dev and canary should be running the same code as prod, so it is critical to find out why prod is not working.
