### ISSUE TITLE
User submitted content: until it's been approved, show it is not live/needs approval to the user

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#1024]
when I submit an event, testimonial, vendor or action, that action shows up for me but it's not clear that it is not live yet.
Can we make it clear? 

Also, it used to be for testimonial that, until it was approved, I could edit it (there was an edit button)  - I'm not sure if this is still the case (at the moment there is a bug that won't allow me to submit a testimonial). We should have that edit button for all user submitted content cards. And also when you click on it, on the indiv action (etc) page:

![Edit button](https://github.com/massenergize/frontend-admin/assets/30277868/6dd97832-c141-4c20-8f94-6e6ddb7242e1)

**Comment by abdullai-t** [comment]
@kaatvds, I have submitted a PR on this issue; here is a demo.

https://github.com/massenergize/frontend-admin/assets/42780120/2a8b58e0-bdf3-4522-8769-97c1a8a642c5

**Comment by kaatvds** [comment]
Looks good.  Some suggestions:

for ACTION: 
for  "pending approval" notification,  is it possible to overlay a "pending approval" banner over the image?  Then it won't take up more space. I can create this for you in canva.
Then, upon hover over the image, a popup says: "You alone are seeing this action that you submitted. You can edit it until a Community admin approves it. To edit, click on the card". 
When they  click >  the indiv action page > have the same edit button as you have in Vendors (square, orange) in the spot you have it there ( there seems to space for that).

For VENDORS
same thing as Actions.

TESTIMONIALS
keep the way it is except on testimonial page, replace current "add a testimonial" text with round , orange "+Testimonial"  and next to it put the same orange/square "edit" button as in vendors.

EVENTS
Same as ACTIONS: don't have "edit" button until one clicks on card. I like how you squeezed the  (square, orange) edit button next to the RSVP button. Most events though do not have RSVP enable: for those it can be the same square, orange) edit button  in that spot.

**Comment by abdullai-t** [comment]
> Looks good. Some suggestions:
> 
> for ACTION: for "pending approval" notification, is it possible to overlay a "pending approval" banner over the image? Then it won't take up more space. I can create this for you in canva. Then, upon hover over the image, a popup says: "You alone are seeing this action that you submitted. You can edit it until a Community admin approves it. To edit, click on the card". When they click > the indiv action page > have the same edit button as you have in Vendors (square, orange) in the spot you have it there ( there seems to space for that).
> 
> For VENDORS same thing as Actions.
> 
> TESTIMONIALS keep the way it is except on testimonial page, replace current "add a testimonial" text with round , orange "+Testimonial" and next to it put the same orange/square "edit" button as in vendors.
> 
> EVENTS Same as ACTIONS: don't have "edit" button until one clicks on card. I like how you squeezed the (square, orange) edit button next to the RSVP button. Most events though do not have RSVP enable: for those it can be the same square, orange) edit button in that spot.

### New Demo
https://github.com/massenergize/frontend-admin/assets/42780120/0cd9aecd-fa58-455c-a7b6-260155267050
