### ISSUE TITLE
Create a way for CAdmins to quickly identify users for a specific action

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-admin#1028]
**User Story.**
As a CAdmin, I want to be able to quickly see which of my users has marked an action to-do (or done or testimonial). So that I can email them about new events, incentives or assistance for that action.

Specs here: https://docs.google.com/document/d/1npKz8qyVW7SvBqy6kJY1mUfZbcWjw7Jq_bSbYjLG33A/edit# 

Note: if a download csv with this information (rather than tying into the dashboard) is easier, that is also acceptable. The priority is to make this available ASAP.

This is one of the most requested data reports from our database and is critical.

**Comment by BradHN1** [comment]
This is done and deployed
