### ISSUE TITLE
can't unshare/remove event from HP 

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#1029]
Enway HP has a Framingham event on it: https://www.energizewayland.org/events/731
I want to take it off my HP and unshare it. I can do neither because I can't see it.

As a Cadmin I go to

1. events in my community; it's not there because it's not my event
2. event sharing: it's not there either
<img width="1450" alt="Screenshot 2023-06-28 at 3 38 07 PM" src="https://github.com/massenergize/frontend-admin/assets/30277868/4860b747-6f22-4703-a493-74ea1ffb515c">

As a superadmin, I do see the event:
<img width="1256" alt="Screenshot 2023-06-28 at 3 40 41 PM" src="https://github.com/massenergize/frontend-admin/assets/30277868/424ff302-00f2-467b-af93-8ad06e868f81">
And I see it is shared with all communities: 
<img width="436" alt="Screenshot 2023-06-28 at 3 42 17 PM" src="https://github.com/massenergize/frontend-admin/assets/30277868/05b5eed7-6507-4d68-9cf5-d1448b505fd9">

then why can't I see it in Enway list? BECAUSE I shared it??

(by the way I can't unshare it there either because the community list that pops up when I click "share event"  deosnt' scroll so I can't unclick Enway (different ticket))

**Comment by kaatvds** [comment]
I just took it off the Home Page but by using the Home Page "page" (under community profile > pages). 
We should potentially remove that redundant function.

**Comment by frimpongopoku** [comment]
@kaatvds  sorry about that. I will find out why some events are not showing on the "others" page. 

About the dialog, I think its probably just not deployed yet, cos when I checked locally with dev, scrolling was active.

https://github.com/massenergize/frontend-admin/assets/26961591/011189de-9d17-42d9-b8b1-8cb83b32dd15



Also about you removing the event via the community profile page, I believe that is exactly how users are supposed to make page edits to any particular page(that reflects on user portal)🤣 🤣. Thats the structure we have. But I get it 🤣 🤣 , I will find out why some events are not showing on the "others" page

**Comment by kaatvds** [comment]
Re removing it on the "Pages": we moved away frm that a while ago, adding that star you see in the screenshot above, at the end of each line on the events list. That's where we're supposed to put it on or remove it from the HP now (but we didn't do away with the old way, which helped me out here, but I wonder if we should remove it).
