### ISSUE TITLE
Clicked on " Review event information.": infinite spinner

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#1031]
A user submitted an event. I got an email, click on the  "Review event info" ([Review event information](https://click.pstmrk.it/3s/admin.massenergize.org%2Fadmin%2Fedit%2F1082%2Fevent/QASE/2kSuAQ/AQ/5d570e81-0e7b-4d9d-9f84-c709c630cd17/1/m1pT6tydXm). and it takes me to admin, then infinite spinner

<img width="1432" alt="Screenshot 2023-06-28 at 8 53 32 PM" src="https://github.com/massenergize/frontend-admin/assets/30277868/5f9cb724-edd0-4d6d-b806-725a9e00b01c">

**Comment by frimpongopoku** [comment]
@kaatvds  I went over this one as well and the results were just like in the other testimonial ticket : https://github.com/massenergize/frontend-admin/issues/1032#issuecomment-1612496834

Everything worked well 🤔  can more people test this?

**Comment by kaatvds** [comment]
Now it works for me too. Can't reproduce.
