### ISSUE TITLE
TinyCloud warnings on EditAction page

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#1039]
**Describe the bug**
We've been seeing the TinyCloud warnings and I think I've figured out that they only happen on the EditAction page, where there are three TinyEdit windows, and only in the second and third window.  It has something to do with hte multiple windows instances.

Perhaps each needs a unique ID, or they can't all be active.

There is some information here on [Multiple TinyMCE instances on a page](https://www.tiny.cloud/docs/tinymce/6/multiple-editors/) and I don't know if this is relevant.

Here is a suggestion which I think might be an improvement (@kaatvds let me know what you think):

Instead of having one or more TinyMCE instances on an edit page, have a field that just shows you the formatted text as a preview, without any of the controls.  When the user clicks on the formatted text, open a dialog which has the TinyMCE editor with its edit controls, and a Cancel and Accept buttons.

**Comment by kaatvds** [comment]
It seems to me that the solution is a workaround that adds a layer of complexity to the admin and gives the admins yet another step. I'd rather  address the cause. There were times we didn't have these warnings, so what changed?

**Comment by BradHN1** [comment]
I think the proposed solution would be an improvement over what we have now.  It doesn't change things, you click in the text window to edit it.  Not more complex than that.

What changed seems to be on the TinyMCE end.  I think they changed something and those warnings started happening.
