### ISSUE TITLE
under "need help?": refer to training course on Resource center

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#1050]
As an admin I need help. I click on "Need help": it takes me to outdated Google docs.

<img width="404" alt="Screenshot 2023-07-19 at 3 13 40 PM" src="https://github.com/massenergize/frontend-admin/assets/30277868/347e0334-3e74-4f55-9d25-b4c55a429004">

Please change the text to:

"Need help? Visit out Resource Center, check out the Website Admin Training course, and sign up by email support@massenergize.org." Add a link under "Website Admin Training"  to 
https://resources.massenergize.org/courses/admin-training

**Comment by BradHN1** [comment]
@frimpongopoku - Kaat asked that the text be changed, not just the link.  Please look at what was written under the figure.

**Comment by frimpongopoku** [comment]
@BradHN1 does this work?

![Screenshot 2023-07-21 at 18 50 49](https://github.com/massenergize/frontend-admin/assets/26961591/4a4ef9e8-9af6-4db8-8f51-9803e161d2c7)

**Comment by kaatvds** [comment]
Can it read: "Need help" (title) "Visit out Resource Center, check out the Website Admin Training course, and sign up by emailing support@massenergize.org." It's one sentence because it's a sequence. Is it possible to have the liked tet be the same size as the other text?

**Comment by frimpongopoku** [comment]
@kaatvds  now? 
![Screenshot 2023-07-21 at 19 49 49](https://github.com/massenergize/frontend-admin/assets/26961591/4ff903be-8738-4b85-8aff-0a931964da51)

**Comment by kaatvds** [comment]
yes, good for now. 
At some point anyone who becomes an admin/signs MOU will automatically get enrolled into the training.

**Comment by frimpongopoku** [comment]
Hmmm, well noted. 

@BradHN1  I have pushed the changes to this PR.
