### ISSUE TITLE
Change your notification preferences - blank screen

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#1064]
**Describe the bug**
From the cadmin events nudge, i clicked "change your notificaiton preferences" (link to https://admin.massenergize.org/admin/profile/preferences) and got a blank screen.

This was in a browser window where I wasn't signed in to the platform or admin, and it didn't take me to a sign-in page.
The error signaled in the javascript window was: Uncaught SyntaxError: Unexpected token '<'

**Expected behavior**
It should take me to a sign-in page.

In another browser window, which had been signed in, it does take me to the preferences page.  **But there is another problem: the link doesn't specify which profile was signed in, so it had me signed in as Super Admin rather than the profile I wished to change the settings for.

For users who have multiple profiles, it should make a good attempt to sign into the correct one to change the preferences**

**Screenshots**
<img width="787" alt="Screenshot 2023-08-21 at 2 05 19 PM" src="https://github.com/massenergize/frontend-admin/assets/12800484/3a296fbf-5b3c-4156-ad15-61b7917408d5">

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version 13.3

**Additional context**

**Comment by frimpongopoku** [comment]
@BradHN1  this seems to work 🤔 

https://github.com/massenergize/frontend-admin/assets/26961591/fbff4533-4f20-4bca-b623-d74fa6b55872
