### ISSUE TITLE
Sadmin can share events with any communities

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#1066]
As a super admin I can share any event with any other community, even if the source community has chosen to share it with only a subset. 

e.g. as a Sadmin I shared the Franklin Harvest Festival with Wayland, while it was restricted to Franklin and Box.

<img width="523" alt="Screenshot 2023-08-22 at 3 04 45 PM" src="https://github.com/massenergize/frontend-admin/assets/30277868/6b4369f5-5f10-4a30-a48d-e3273fd99a21">

If the orginial community has made the event fully unsharable, then the share button on the event form is greyed out, which is proper. 

I think the **solution** is to grey out that button fro the Sadmin in the case of selective sharing as well.

**Comment by BradHN1** [comment]
Sadmins have the power to do this- however I don't agree that sadmins should feel entitled to share events if the community has not shared them.
