### ISSUE TITLE
Deleting Users from All User page doesn't update the page

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#1069]
**Describe the bug**
If a cadmin or sadmin deletes users from the All Users page, the page doesn't update and the users still show up until the page is refreshed.  In the example below, I deleted the 5 users "A A" and they still appear.  

![Screenshot 2023-08-24 at 5 34 42 AM](https://github.com/massenergize/frontend-admin/assets/12800484/ad7111ca-13f6-40a2-95e7-cf36d8584c2b)

**Comment by abdullai-t** [comment]
This issue seems to be resolved in canary. However, there is a new bug related to deleting items that I am currently working on fixing.
