### ISSUE TITLE
Nudge enabling and scheduling for community admins

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#1075]
**User Story.**
As a 
**Community Admin**
I want 
**some control of enabling/disabling and timing of nudges going out to community members**
So that 
**they don't interfere with my newsletter or other communications and I can control the timing of my communication from both the platform and other sources (newsletter, etc.).**

The user nudge generator is a task which runs daily, sending a nudge to users in communities with nudges enabled (set through feature flags) when there is content to send.  Though default user settings have nudges going out weekly (at most once a week), users can select daily monthly or disabled entirely. 

Feature flags are controlled by superadmins, so  the overall nudge functionality for communities can only be enabled by superadmins, when requested by a cadmin.  What this ticket describes is the mechanism for requesting the functionality be enabled for Community Admins, and the ability to temporarily enable or disable such messages going out.

User experience for Cadmins:

**DISCUSSION ITEM:**
PRIOR - On the community profile page, in the box currently titled "More Details" (which should be renamed to "Community Management"), a new section "Platform Features", with one item "User Nudge Messages".

AIMEE SUGGESTS: we should add this feature under Settings - Communication preferences instead.

At the top of the existing box, add a title " Your Personal Communication Preferences."

Then add another box with the title "Control Messages Sent to Your Community Members"

Explanation under the title a short explanation on what nudge messages are:

"You, as the community administrator, have the ability to enable, pause or disable various emails sent automatically from your MassEnergize platform. These messages will be sent from your community's email address and include your community logo. The intent here is two-fold: bring your members to your site more frequently and to reduce your communications work as a community admin. 

Your users with a profile have the ability to control the frequency they receive messages (default weekly, other options are every two weeks, once a month or never). Guest users do not receive these emails.

Please enable, disable or pause such messages, and select which content would be included, using the choices below."

Emails to users (display as radio buttons: with the appropriate button filled in based on the current settings from the back-end; set default as enabled)
Enabled
Disabled  
Paused  - if currently paused, this text will say "Paused until [date]"   

Content of emails (display as radio buttons; set default to check all)
New upcoming events
New teams (coming soon)
New testimonials (coming soon)

If the user nudge feature flag is not enabled for the community, and the CAdmin selects "Enabled"  the dialog should show a message "User Nudges are not enabled for your community.  Enabling nudges will request a Super Admin to enable that functionality for you, which should take place within 48 hours."

**Acceptance Criteria**
- [ ] If the CAdmin selects "Paused", then this brings up separate pause control dialog (see below)
- [ ] Button: Submit submits the information and closes the dialog
- [ ] Button Cancel closes the dialog without submitting
- [ ] Button: Send a sample user nudge will send a user nudge to the cadmin's email (even if the feature flag is not enabled and even if the emails to users is Disabled)
- [ ] Pause control dialog has a couple options
- [ ] Button: Add a temporary pause, allowing you to select a start date (default today) and resume date
- [ ] Button: Pause until further notice
- [ ] List box - lists the pause intervals.  can select one of those intervals and get option to delete it
- [ ] Button: close

**Comment by apowelka** [comment]
![image](https://github.com/massenergize/frontend-admin/assets/60662056/d1f3afe6-6a0e-41f1-9de0-9043b6e5acc9)
we should add this feature under Settings - Communication preferences instead.

**Comment by apowelka** [comment]
@BradHN1 - I removed new actions from the list for now because I think most communities have fairly static actions and we should think about this. I do think a "new rebates" or something would be awesome as a communication nudge.

**Comment by BradHN1** [comment]
@apowelka - the control should be under the community profile page I think, because if you happen to be a cadmin of multiple communities you need to have control independently for each community.  
Preferences under settings is your preferences for communications to you as a cadmin.
