### ISSUE TITLE
Can't delete an event: thinks its a template but it's not

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#1076]
As a superadmin I copied an event then decided to delete the copy.
Admin won't let me, says I can't delete template. But it's not a template.
<img width="644" alt="Screenshot 2023-08-25 at 1 34 11 PM" src="https://github.com/massenergize/frontend-admin/assets/30277868/60eec171-5f12-468f-8909-651ae4b3d4e6">
<img width="542" alt="Screenshot 2023-08-25 at 1 34 25 PM" src="https://github.com/massenergize/frontend-admin/assets/30277868/4ba6add3-d26a-4002-97ff-47bf483a7183">

**Comment by frimpongopoku** [comment]
@BradHN1 I was able to reproduce it, its an actual bug. The good news is that, its one of the many things in DEV that have not made it to PROD yet. So anytime we make a push from the DEV to PROD, all should be fine.

**Comment by apowelka** [comment]
Adding comments from #1076 that was closed because there is a response that shows an incorrect assumption or display.I accidentally created 3 copies of an event. I went to delete them, but I get an error message saying that I cannot delete templates. I did not designate these as templates. I am signed in as a community admin. Its the first 3 events, 1283-1285, in the photo.

**Comment by apowelka** [comment]
I am not able to see or edit whether or not my events are templates.

![image](https://github.com/massenergize/frontend-admin/assets/60662056/7457f7be-a98d-4118-a528-8c828f7a2f73)
![image](https://github.com/massenergize/frontend-admin/assets/60662056/d7c66acf-64f9-4ad5-a3fa-86dca5453c92)

There is no displayed function to make or turn off a template
![image](https://github.com/massenergize/frontend-admin/assets/60662056/17da6f09-114a-462b-855f-7991ffa5cf2c)
![image](https://github.com/massenergize/frontend-admin/assets/60662056/a3114cbd-f434-4844-b9f9-1cadd5610d56)
![image](https://github.com/massenergize/frontend-admin/assets/60662056/314c474d-a589-4603-aef5-3a902c522078)
![image](https://github.com/massenergize/frontend-admin/assets/60662056/3c1c38af-0263-4992-a3bf-b471a9a94cb4)
![image](https://github.com/massenergize/frontend-admin/assets/60662056/fc7786b9-4b8c-41c2-84fe-9d4c98c2ada4)
