### ISSUE TITLE
Add Building and room fields to event address

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-admin#1077]
As a CAdmin, I want to be able to tell my users what building and room an event is in. So its easier for them to identify. AND, it would be really helpful as a CAdmin not to fill in my own community name for every event.

Example of how I'd like it:
Framingham Main Library (this is the missing field called Building)
Costin Room (a 2nd missing field called Room)
49 Lexington St. (Street Address)
(Unit number)
Framingham, MA (autofill these with the community)

![image](https://github.com/massenergize/frontend-admin/assets/60662056/525856a7-79bd-474e-b800-0d0c49dfffb5)

**Comment by apowelka** [comment]
accompanying user portal ticket #1256

**Comment by abdullai-t** [comment]
@apowelka,  is this what you meant?
<img width="1105" alt="Screenshot 2023-08-29 at 10 10 08 AM" src="https://github.com/massenergize/frontend-admin/assets/42780120/c1075790-531b-4b99-bc45-8ee3cfefe2f3">

**Comment by apowelka** [comment]
yes, but I would order it:

Building name
Room (take off "number")
Street address
Unit number
City
State
