### ISSUE TITLE
Creating a team leads to a blank screen

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-admin#1120]
As a CAdmin, if I click on Create Team, a blank screen appears.

Reported by on a mac in 2 browsers. I reproduced on a pc in chrome.

![image](https://github.com/massenergize/frontend-admin/assets/60662056/b0c07a21-b443-4b60-a24c-c93ae1325707)

**Comment by BradHN1** [comment]
I fixed this recently, it is issue 1115.  Will ask to have it merged to Canary and deployed.
