### ISSUE TITLE
Super admin delete users - message "Unable to delete users who are admins or members of multiple communities"

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#1124]
**Describe the bug**
Super admins should be able to delete users, even if they are members of multiple communities.  I tried to delete the profile for Maya Spalding-Fecher (a prior intern) but was unable to do so.

**To Reproduce**
1. Go to All Users
2. Click on the user Maya Spalding-Fecher
3. Choose the trash can to delete the user

**Expected behavior**
The user profile should be deleted.  This may be an issue with the API

**Screenshots**
<img width="1382" alt="Screenshot 2024-02-02 at 5 17 44 PM" src="https://github.com/massenergize/frontend-admin/assets/12800484/3cfc1c27-18c9-4197-a9f9-bedaa261a84c">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abdullai-t** [comment]
My question here is: Should super admins be able to remove other super admins? I believe that removing super admins should be reserved for the mission control site.
