### ISSUE TITLE
Testimonials - live edit rank (like actions)

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-admin#116]
On the "All Actions" page, a Cadmin can change the rank right on that screen. Super helpful. I would like to see that functionality duplicated for testimonials.
Label: enhancement

**Comment by kaatvds** [comment]
Ranking works on the list in Cadmin. It also reflects on the comm portal. But it does not reflect/is retained in cadmin interface indiv testimonial form.

**Comment by kaatvds** [comment]
in safari

**Comment by kaatvds** [comment]
Worked on dev but not in CAN:
Prius prime rocks is numbered 10  on its infiv form 
![image](https://user-images.githubusercontent.com/30277868/98294620-3d512300-1f7e-11eb-8cf8-41b266af8655.png)
but in list  it shows up as 0 (though it did get bumped down, as before I renumbered it it was at the top)
![image](https://user-images.githubusercontent.com/30277868/98294710-6671b380-1f7e-11eb-8b60-8de97e865c06.png)


Same when I changed the number in the List (box): it bumps it down and number is retained on indiv testimonial form but in the list it is still shown as 0
