### ISSUE TITLE
Choice selection (radio button) for Notification preferences failing

### ISSUE THREAD

**Issue by boatengjephthah27** [massenergize/frontend-admin#1176]
### **DESCRIPTION**
Radio buttons for selecting a notification preference fails to select

**Acceptance Criteria**

- [x] Admin should be able to select or change preferences for notifications

###### UX Design
Insert figma link or link to design

###### Technical Considerations
Insert technical considerations

https://github.com/massenergize/frontend-admin/assets/104381959/1d928be4-516e-4a83-97b0-aa5712704659

**Comment by frimpongopoku** [comment]
This is not a bug @boatengjephthah27 I think currently the options are setup so that you can only click on the round labels. When you do that, everything is fine.
