### ISSUE TITLE
Removing community custom domain not allowed

### ISSUE THREAD

**Issue by boatengjephthah27** [massenergize/frontend-admin#1203]
**Describe the bug**

Choosing to remove a community's domain gives a success response but doesn't remove

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to  All Communities list, as Cadmin or Sadmin
2. Click to view a community
3. Click on edit community info
4. Try removing the custom website domain

**Acceptance criteria**

- [ ] Cadmin or Sadmin should successfully remove a domain if they want to
- [ ] On success page shouldn't give a 404 error page before it tries to fetch data or load page to show the forms (should just show a loader right from the onset to when page finally loads)

**Screenshots/videos**

https://github.com/massenergize/frontend-admin/assets/104381959/d0e6d7e2-2896-4d69-b5b3-632a2a38ee0e

**Additional context**
**********

**Comment by BradHN1** [comment]
This is a low priority.  Community Admins should not be able to change subdomains, and super admins can do that though Django admin if needed but it almost never is.
