### ISSUE TITLE
Cadmin dashboard: make tiles up top static

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#129]
We will do an overhaul of the dashboard at some point but for now can you make the boxes up top NOT clickable. Right now when you click e.g.  "59 actions" you don't get those 59 action but instead all actions which you can get to in sidebar>

**Comment by kaatvds** [comment]
no change, reopening.

**Comment by BradHN1** [comment]
@kaatvds - is it just that the lists include templates?

Clarify that the numbers don't include templates.  Not a priority
