### ISSUE TITLE
make duplication of vendors possible for Cadmins

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#138]
Potentially we could make a "template" vendor so that each time a Cadmin puts in a new vendor they can decide if it's one worth sharing   with others.

**Comment by ellentohn** [comment]
This failed for me. i did it on https://admin-dev.massenergize.org/admin/read/vendors - 9.9.9. 

When I clicked duplicate and open in new tab -- it took me to the list of vendors again. I could edit a vendor but not duplicate. Happy to do a share screen and show you this @Opoku-Agyemang . 

i am around today and after 830 pm today. I know @kaat is anxious to push the code that you did with frimpong on the items newton requested. So if we can't get this into this deploy we can pull it for another day.

**Comment by ellentohn** [comment]
thanks!

**Comment by kaatvds** [comment]
Turns out to make this happen through templates is a larger change and will have to wait. In the meantime however when a community creates a vendor they can assign it to more than one community. So let's say Lincoln sees a great vendor for Wayland: they contact Wayland and then Wayland an  add them in that dropdown box. This mean that the vendor description needs to be generic enough. Let's go with that.
