### ISSUE TITLE
Cadmin interface: Home page: question about displaying icon boxes

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#148]
the form asks “Should we display summary Stats on your home page?” but it should read "do you want to display the icon boxes?"

![image](https://user-images.githubusercontent.com/30277868/80249660-3dbc4900-8640-11ea-9887-5e444d5a4f2a.png)

**Comment by BradHN1** [comment]
Simple fix.  Moving to in-progress
