### ISSUE TITLE
Ranking on Actions doesn't work: is not retained when changed in list

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#149]
The ranking in the list doesn't work anymore.

**Comment by kaatvds** [comment]
On the all actions page the actions have ranks of 1,1,1... 2,2,3,3 etc
![image](https://user-images.githubusercontent.com/30277868/81584323-9c8ffb00-9380-11ea-8b8e-368904e2977b.png)
But on their indiv forms they still have the given rankings, e.g. "109".
![image](https://user-images.githubusercontent.com/30277868/81584433-bf221400-9380-11ea-97d5-9a28e4466d1d.png)

**Comment by BradHN1** [comment]
Fixed in branch 'carbon-goals'

**Comment by BradHN1** [comment]
This is back to the way it was before - You can change the ranking, but when you load the all actions page the ranking fields are all 0.
Tested in Dev - filtering on NoWhere community.  Should be 10,20,30,40.
Functionality partly works: you set a number and it does get set on the back end, but always appears to be reset to 0.

**Comment by kaatvds** [comment]
not fixed so reopening
