### ISSUE TITLE
in what order are Users listed? Can we have column with ID or date?

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#151]
Wondering how new users are added to list. List doesn't seem  (by default,  when you land on it) to be ordered in any particular way. 
Would it be possible to assign ID's to them (like with Actions etc.): would be handy to then be able to order them to latest joined first.

**Comment by BradHN1** [comment]
There is already a field created_at which has the creation date.  How about adding this as a final column, and sorting on it?

**Comment by kaatvds** [comment]
I'm not sure I see the fix here? or what to test?

**Comment by kaatvds** [comment]
still can't see how this is fixed...

**Comment by BradHN1** [comment]
I think users were listed in order created.  
Instead change ticket to not only list in order created (default reverse - most recent to less recent) and add a column of the date joined

**Comment by kaatvds** [comment]
Hi Brad, that (assign some sort of ID, which can be the date created) was the ask when the ticket was created. Should the ticket be in QA? Is there a code change associated with it.... Not sure what to do with it.

**Comment by BradHN1** [comment]
Lets leave it open, and change ticket to add the date column so it can be sorted by like the other columns.  Doesn't that solve the issue?

Also add date subscribed column for subscribers, and date submitted for testimonials, date sent for messages while we are at it.

**Comment by massenergize-admin** [comment]
@kaatvds Users are pulled up with the most recently created coming first.  So essentially descending order of date of creation.

**Comment by kaatvds** [comment]
When opening "users" YES, last one signed u shows  up first.
But if I now sort according to any column I can't go back to that original sorting. Adding a column with a date (when joined) would be great.
The work around is just to open the list again for the initial sorting, so for now it's okay, but we may want this later. Am moving to validated

**Comment by kaatvds** [comment]
not fixed so reopening
