### ISSUE TITLE
testimonials can only be left by users with profile: open up to others?

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#154]
For the moment testimonials can only be left by users with a profile. Wondering if we could also ope it up to users who want to leave a testimonial but don't want to create an account: in that case the Cadmin creates  new testimonial. 
At the moment when cadmin fills it in and put the user's emai (NOT connected to an account) the output is "anonymous"

**Comment by BradHN1** [comment]
Duplicate to Admin #158
