### ISSUE TITLE
Vendor website should be optional

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#164]
Make entering a vendor website optional.

**Comment by BradHN1** [comment]
Don't know what is wrong here, since form appears to make website optional
If I don't specify a website, and hit submit, get the message:
Error Occurred: You are Missing a Required Input: Website

**Comment by kaatvds** [comment]
That still persists: if no website , error.
![image](https://user-images.githubusercontent.com/30277868/83955460-308aa080-a821-11ea-956b-054b1c9ecc23.png)
