### ISSUE TITLE
Implement help modal

### ISSUE THREAD

**Issue by OrlyStrobel** [massenergize/frontend-admin#178]
The cadmin instruction videos (can currently be found in the MEServices shared drive--> Training--> Cadmin instruction videos) should live in the information (?) icon on top left of interface and also on the dashboard at the very bottom as the final item before "Signout" 

![Screen Shot 2020-05-20 at 5 38 47 PM](https://user-images.githubusercontent.com/65621001/82500296-20549080-9ac1-11ea-9504-3f398d226918.png)
![Screen Shot 2020-05-20 at 5 39 02 PM](https://user-images.githubusercontent.com/65621001/82500304-22b6ea80-9ac1-11ea-991f-64706c7b747d.png)

**Comment by jkatofsky** [comment]
Could you elaborate on which content will be going where, and how it will be displayed? @OrlyStrobel  The following is how I'm interpreting it at the moment, but please let me know if any part of it is inaccurate:

When you click the (?) icon, it opens a pop-up menu that contains the instructions video corresponding to the specific page you're on (when applicable). As for the menu item above "signout", that would bring you to a page that contains all of the videos.

**Comment by OrlyStrobel** [comment]
Hi @jkatofsky yes, exactly how you are describing it is how I meant it. For the (?) it would be great to have each instruction video apply to the corresponding page and to have an instructions video "menu" (or Table of Contents) right above the "signout" button. Let me know if there is anything that is still unclear!

**Comment by jkatofsky** [comment]
https://stackoverflow.com/questions/43880756/streaming-a-video-from-google-drive-using-html5-video-tag/52397246#52397246
https://stackoverflow.com/questions/40951504/how-to-embed-videos-from-google-drive-to-webpage

**Comment by jkatofsky** [comment]
I've started to implement this, and I noticed that there are multiple instruction videos for a given piece of information. I.e. Creating/Editing/Copying an action. The videos also span multiple pages of the portal. As a result, it's hard to find a one-to-one correspondence between the (?) icon on a given page and a single instruction video.

There's a few ways to address this:
- when on _any_ of the (for example) action-related pages, the (?) icon will open one dialogue box which contains _all_ of the action-related videos. You could click through them, in a similar way to clicking through the different sections of the current placeholder dialogue box that it opens.
- only create the all-videos page and make the (?) icon to the all-videos page, automatically scrolled to the relevant section
- only create the all-videos page and do away with the (?) icon

@OrlyStrobel @kaatvds @ellentohn thoughts?

**Comment by jkatofsky** [comment]
The plan that Ellen and I came up with:

- same popup on every page, get to it from a button that lives on the top
- two bullets in pop-up: written instructions drive link and video table of contents drive link
- rename “guide” to “need help”, maybe change icon, maybe remove tooltip
