### ISSUE TITLE
Community Admin data download

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-admin#180]
Admins need an easy way to download data from the Admin portal. By data, I mean a csv file with all users and subscribers. Attributes for the users need to include their email, community, team(s), actions done, actions to do, action impacts for both of those, cumulative carbon emissions reduced. This will be incredibly useful and allow admins to easily figure out trends in their community, compare teams, etc. Let's use the power of your work to its full potential!

**Comment by apowelka** [comment]
Rows - users
Columns:
Name
Email
Each Action (values are to-do/done/blank)
Each Team

(Do NOT include carbon impacts for each action). 
SEPARATE CSV download for all actions with their tags and carbon reductions.

**Comment by jkatofsky** [comment]
Two routes to be added to API to support this ticket. Current name ideas:

- `csv.users`
- `csv.actions`

Front-end admin download feature will live on the profile of a community.

**Comment by ellentohn** [comment]
names look good. 

Would be good to be able to download:

all users
all actions
then a combo of the 2

et

**Comment by jkatofsky** [comment]
@apowelka @ellentohn What are your thoughts about the placement of the download links on the community profile page? I was thinking of adding a third section at the bottom of this page called "Data Downloads" which will contain an explanation of, and buttons for, the user and actions CSV downloads.

<img width="531" alt="Screen Shot 2020-07-02 at 5 16 45 PM" src="https://user-images.githubusercontent.com/13226824/86409926-d21dda00-bc87-11ea-90c3-07e9d46459c9.png">

**Comment by ellentohn** [comment]
I think its fine to have a third section below; the # actions goalsk and #Household goals
