### ISSUE TITLE
BUG Creating an Event

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-admin#202]
Trying to creat an event in the CAdmin, get this error:
![image](https://user-images.githubusercontent.com/60662056/91756914-8a3e0500-eb9b-11ea-922e-ea16743c55bb.png)

**Comment by BradHN1** [comment]
I think this bug was due to AWS keys being changed, that it didn't save the image file.

**Comment by kaatvds** [comment]
@apowelka was this in dev or prod?

**Comment by apowelka** [comment]
this was in prod. I just created a new event and it worked great.

**Comment by kaatvds** [comment]
works in dev too, moving ticket to valdiated
