### ISSUE TITLE
Dev: sign in as community admin, infinite loop

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#207]
Signing in as bradhn@mindspring.com, the message "Hold tight, I am fetching data from the database.  Almost done..." is in an infinite loop, with the progress bar cycling.
i

**Comment by jkatofsky** [comment]
A comment on this: the issue is that the frontend page doesn't redirect. The login itself appears to succeed - try navigating directly to the URL you wish to access after clicking the login button.

**Comment by BradHN1** [comment]
Sometimes, when re-signing in, the redirect doesn't work, so this is what I see
![Screen Shot 2020-09-11 at 3 12 12 PM](https://user-images.githubusercontent.com/12800484/92963899-32c45280-f441-11ea-89e7-c07029c29df9.png)

**Comment by apowelka** [comment]
Logging in on a PC, I also see the infinite fetching data loop. I do not go back to the login screen like Brad. I also can just go ahead and click on a community and that works (navigates me to a new page).
