### ISSUE TITLE
Dev: Community profile page, click Publish or Unpublish button doesn't work

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#212]
Appears to get error return from API:

Error from javascript console:

{data: null, error: "Community has no field named 'is_dev'", success: false}
data: null
error: "Community has no field named 'is_dev'"
success: false

**Comment by apowelka** [comment]
DEV: clicking unpublish changes nothing and sends you to the dev site. clicking Go Live does same thing. Clicking preview sends you to the dev sandbox. PC/Chrome
