### ISSUE TITLE
Dev: View list of events:

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#216]
No events listed ("No matching records found")

Error from javascript console?

data: null
error: "Field 'id' expected a number but got 'undefined'."
success: false

**Comment by apowelka** [comment]
Confirmed - no events displayed. However, one may create a new event by filling out the fields and it does display on the community portal but not upon the CAdmin site. PC/Chrome

**Comment by BradHN1** [comment]
Fixed in API Store/event.py
Admin portal could be fixed so community_id not passed as 'undefined'
