### ISSUE TITLE
Dev: View list of teams

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#217]
List of teams doesn't show.

Error return from API? 

data: null
error: "Field 'id' expected a number but got 'undefined'."
success: false

**Comment by BradHN1** [comment]
Fixed applied in API Store/team.py
Admin portal could be fixed so community_id not passed as 'undefined'

**Comment by apowelka** [comment]
Test failed on 9/18. Created a new team just fine - it shows in the portal. BUT it does not dsplay in the CAdmin so no way to edit a team.
