### ISSUE TITLE
DEV: Home Page events selection - can't remove expired events

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#219]
On Dev for community Nowhere, can't change events which are listed once the dates are passed.

![Screen Shot 2020-09-11 at 11 40 22 AM](https://user-images.githubusercontent.com/12800484/92945691-9fc8ef80-f423-11ea-8a9e-d5a65e0558f5.png)

**Comment by apowelka** [comment]
agree, not all events are displayed on the drop-down. A newly created event is displayed. PC/Chrome

**Comment by kaatvds** [comment]
And it's an issue on DEV too so moving it to TO bec it's an important one
![image](https://user-images.githubusercontent.com/30277868/94849779-ef338780-03f3-11eb-9b9e-3bc69640663d.png)
Can't delete the expired event ("Please select an option") and that deleted/unlived event show as a FOURTH event on the home page.
![image](https://user-images.githubusercontent.com/30277868/94849886-14c09100-03f4-11eb-80bf-b17c73f4fd76.png)

**Comment by kaatvds** [comment]
I deleted the expired event and this worked. Not ideal but workaround for now.
