### ISSUE TITLE
Create a Goal

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-admin#223]
This is an odd ticket with multiple issues.

First, when I follow the link, I can enter data for goals but I cannot save. The error message is to enter a goal target date yet there is no field to do so.

Second, I have no idea how to navigate to this page from the CAdmin portal: http://admin-dev.massenergize.org/admin/add/goal. Goals display on the community profile, but are not included in the pages, etc. https://admin-dev.massenergize.org/admin/community/98/profile.

Third, for discussion by MassE team, I think having a space for a carbon goal is a good idea but should be a separate process. Also, it is unclear if this is a total of all actions and households and carbon, I think so, but unclear. And where is that displayed on teh user portal.

**Comment by kaatvds** [comment]
This works: The way to find this is to say yes to goals on Home Page. And you can choose to display carbon goal, or not. Closing ticket
