### ISSUE TITLE
DEV: can see cadmin interface with unique url even when not signed in

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#237]
signing into the admin portal. I used the url "https://admin-dev.massenergize.org/admin/read/users" and it took me straight there, didn't ask me to sign in. In the corner it says just "Howdy," and then a smiley face: so it is not recognizing me?  The usual stuff at the top of the left menu is also blank. And when I click on All actions: blank list. But when i click on Add Action: I get the form... get stopped at submit: Permission denied.

![Screenshot (713)](https://user-images.githubusercontent.com/30277868/96172037-ca5f0a00-0ef3-11eb-96fb-0305acd9cfec.png)

 So anyone with a url can see our interface (but can't see data or do  anything).

**Comment by Davidjwkinghorn** [comment]
I believe this has been resolved. I'll check before closing this issue.
