### ISSUE TITLE
changes to email to new Cadmin: Bad link among them

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#238]
text of email is a mix of fonts: make all fonts same
also align all to the left except titles

change paragraph breaks under "What Next", change order, and add "and teams (in **), like so:

Now that you are a community admin, you have access the MassEnergize Administrator's Website.
You can customize your community’s home page, publish actions and events for your community, add service providers and approve testimonials **and teams.**
You will need to log in often to check for messages from users.
You can also add other admins - but when you do so, let us know.
You may also preview unpublished changes in your Community Portal's Sandbox.
Just log in to your MassEnergize account on the admin site to get started. 

At end of "Need help ?" delete space before question mark

Under that: 
"If you want a reminder about how it all works, check out these instructional materials ." DELETE the space before the full stop at the end.
change link at "these instructional materials" to https://drive.google.com/drive/u/0/folders/1cswbcF_aKwJCPXIQ3eD4NUpu2dRWa9cM
Add: "Request access if you don't have it yet."

In "Also join our Slack Community Group and let's discuss further." Change link at "Slack Community Group" to ???????

at end
change email: "Have fun, and don’t hesitate to reach out to us at support@MassEnergize.org if you have questions."
And make that email a link

**Comment by kaatvds** [comment]
Still has link to wrong instructions in it: link should be:
https://drive.google.com/drive/u/0/folders/1kefvOkIqAte2QjU8O-zbHQ_ucMWHKfMz

**Comment by kaatvds** [comment]
This is still a bug

**Comment by BradHN1** [comment]
Create instructions on DNS to go instructions.massenergize.org - redirect to a particular google drive link

**Comment by BradHN1** [comment]
Fixed in API branch BHN-fixes
