### ISSUE TITLE
DEV: 2nd testimonial photo default

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-admin#242]
Prior ticket [#391](https://github.com/massenergize/frontend-portal/issues/391) that mentioned form reset for testimonials upon second testimonial submission is fixed. However, when testing this, creating a second testimonial works for the user. It then appears in the CAdmin page for approval. Upon approval, a first testimonial accepts the user-submitted photo. A second testimonial defaults to a lightbulb photo and the title/catchy line formatting appears to be goofed up as well.

You can see in this image the first testimonial at right has the correct image and formatting, the second at left does not (photo should be a sun).
![image](https://user-images.githubusercontent.com/60662056/97006973-a8c2db80-150e-11eb-8e56-eb30bb81f549.png)

RELATED ISSUE: should a CAdmin be able to see the photo attached by a user for a testimonial? I do not see any.

**Comment by frimpongopoku** [comment]
I do not think this is a problem anymore 🤔
