### ISSUE TITLE
CAN: Can't create new community 

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#253]
after submit just kept on spinning

![image](https://user-images.githubusercontent.com/30277868/97750624-88bf8900-1ac7-11eb-8f21-4eb679c5ec02.png)

**Comment by kaatvds** [comment]
turns out it DOES create the communnity: it shows up in the list of All Communities. But it's not clear after pressing submit.

**Comment by BradHN1** [comment]
Fixed in API branch BHN-fixes
