### ISSUE TITLE
Admin/Download users - add teams

### ISSUE THREAD

**Issue by ellentohn** [massenergize/frontend-admin#268]
The download option under the main page - for download users. Can we add a column to show the "team" and "subteam" for each user on this main .csv file. As a Cadmin I want to be able to sort by team and see for all those folks on a team -- which actions they have taken. The other download option we have of "teams" shows aggregate #s not by person.

**Comment by kaatvds** [comment]
2 decisions:
add a column on the all user download that lists all the teams they're part of (with comma in between: but you can't sort by that then)..... Ellen will ask John about this for Excel
on cadmin team page: download basic info (button is there already) + add extra button: download with actions.

**Comment by BradHN1** [comment]
Done with changes to Admin portal (branch BHN-minorfix) and API (branch BHN-fixes)
