### ISSUE TITLE
testimonial: If "other" is selected and company name provided, Cadmin can't see it

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#28]
if user leaves an "other" as under "Who helped" (which is an a great option)  it can't be seen by Cadmin in that testimonial's form...

![image](https://user-images.githubusercontent.com/30277868/73187246-1f04ef80-40ef-11ea-98a3-2e575efb5c70.png)

**Comment by Opoku-Agyemang** [comment]
* Put it in the testimonial view not in the testimonial list view
