### ISSUE TITLE
templates: Only allow Super admins to make templates

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#280]

**Comment by kaatvds** [comment]
For Cadmins:
Remove "Is this a Template" all over (actions, vendors, etc)
(we want to create a different way for cadmins to nominate actions for template status)

Is it possible to remove it for Cadmins but keep it for Sadmins? (not priority)

**Comment by Davidjwkinghorn** [comment]
@frimpongopoku 

Community admins community selection should be mandatory. If a community admin is only an admin of one community it is selected by default.
