### ISSUE TITLE
User signed out after an hour, whether or not actively working

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#281]
Refresh cookie while working so this doesn't happen

When you aren’t signed in, the site doesn’t tell you but you can tell since it says “Howdy” without a name.  It should take you to the sign-in screen when that happens

**Comment by ellentohn** [comment]
@BradHN1 -- this did not work for me; I had the browser open for an hour or 2 and when I went back it  had logged me out -- not sure how else to test it
