### ISSUE TITLE
Photo resizing using resolution rather than cropping - all uploads

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#288]
For all photo uploads, for pictures over a certain size (perhaps 1024 width) compress locally to be that maximum size when uploading.  Keep aspect ratio constant.

Use react-image-file-resizer or another library to do this.

On the community platform this is for testimonials creation and editing (next ticket); and team creation and editing.

Corresponding ticket on admin portal for all other image uploading

**Comment by Davidjwkinghorn** [comment]
@frimpongopoku does the media library handle this?

**Comment by Davidjwkinghorn** [comment]
Info from duplicate [issue 640](https://github.com/massenergize/frontend-portal/issues/640).
> All the pics on EnWay are 4:3. When uploading the crop box shows them in their entirety. Yet on the homepage they are cropped on all sides.
> I am trying to add white strips on left and right of middle picture to get the picture defined better. With this cropping that won't work.

**Comment by frimpongopoku** [comment]
@Davidjwkinghorn, not yet. But if it becomes top priority, it can easily be done.
