### ISSUE TITLE
Cadmin import/export actions, events, and testimonials from google docs directly

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#299]
This would require using the Google Docs API to extract the different sections of action content from the google doc and fill in the new Action on the Admin portal.

And the reverse would allow exporting from the Admin to a google doc of the same format.

**Comment by Davidjwkinghorn** [comment]
Info from duplicate [ticket](https://github.com/massenergize/frontend-admin/issues/580).
> Cadmins should be able to export or import site content for one item (Action) specifying a Google Doc. Importing will require plenty of error checking, and should overwrite the content from within the content editor window, but not submit to the API until cadmin has a chance to review.

> Format of doc should be the same as what we currently use. First step is to specify what that format is since it is pretty free-form.

> Useful feature would be to be able to export all actions or all site content to a folder on Google drive

> Use API for google drive and docs

**Comment by BradHN1** [comment]
Redundant
