### ISSUE TITLE
Testimonials: in list have approved/not approved

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#31]
Cadmins looking at the list testimonials cannot at present see which ones are not approved - so which ones might be new and not looked at yet. Add a column with approved/not approved for quick overview. Sacrifice the image column if more space needed.

![image](https://user-images.githubusercontent.com/30277868/73193200-31cff200-40f8-11ea-90b7-6ae48393d593.png)

**Comment by ellentohn** [comment]
This works. But wonder if we can adjust the column widths to make the headings on "live" and "approved" more readable. 

Also in the filtering, we can filter on approved -- All/No but there is not filter for "Yes" as we have for the Live -- under actions. I think this is ok but if we could add "Yes" to both the Live option and approved that would be good but not essential. 

And the filter screen shows some odd boxes, not sure what they are referencing... 


![image](https://user-images.githubusercontent.com/60329553/75037637-a6414b00-5482-11ea-9134-7478f0bfd11c.png)
<img width="617" alt="Screenshot 2020-02-21 08 13 24" src="https://user-images.githubusercontent.com/60329553/75037658-ae998600-5482-11ea-8a26-c7073b765ca2.png">

**Comment by ellentohn** [comment]
@Opoku-Agyemang when I tested this as a super Admin it worked perfectly I can filter for Live (y/n/all) and approved Y/N/All 

But when I log in as a Cadmin under etohn@comcast.net it does not give me the sam filtering options. It just gives me Live (All/N) and Approved (All/N) in neither case does it give me a "Yes" option. Which is odd that it is different for the Cadmin vs. Super Admin
