### ISSUE TITLE
when creating new community: clea up preloaded text in icon boxes

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#337]
When a new community is created (which happens at the beginning of Cadmin training)  the home page icon boxes are frontloaded with text that exceeds the character limit. This means that when you want to  change anything on thee home page, you  can't submit until you've addressed that char limit  error.
Can we frontload it with much less text? It would help in the training.

![image](https://user-images.githubusercontent.com/30277868/120812432-f67ada00-c51a-11eb-877b-419f24093871.png)

**Comment by BradHN1** [comment]
fixed, will deploy tonight
