### ISSUE TITLE
Events: redesign input of what events to show on home page 

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#366]
Collecting some event ideas here:

at the moment, you have to go to the community profile > pages > home page button on admin and there select which events to show. 
Would be easier to have this in the indiv event creation form - or even better: in the all Events list...

**Comment by abdullai-t** [comment]
@kaatvds, here is a demo
https://user-images.githubusercontent.com/42780120/227509497-ed6d5f0d-067a-45fa-9fa6-ca9b4f05ac87.MP4

**Comment by BradHN1** [comment]
@kaatvds - I don't like the feature of asking a community admin whether to exclude certain events from the events nudge.  It is one too many questions and I don't understand the use case.  If a user wants to be notified about upcoming events, I think they should be notified.  Are you ok with that?

**Comment by apowelka** [comment]
@BradHN1 - kaat is not referring to nudges. She is saying to better integrate the process to select which events to display on the home page with the actual events page.

So, add a checkbox on events to "display on home page"

**Comment by BradHN1** [comment]
I like the selecting of events on the event list, but visually the contrast is not good enough between blue (not selected) and green (selected).  I think it should be grey like the not live button, not blue.  And I think we should make it a star, not a picture of a house, for "Featured Event" and we can extend that feature to Actions, Testimonials, or other content if we decide to.
