### ISSUE TITLE
Import users via CSV

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#376]
Testing @isha-san 's changes for importing users in admin portal.

On community profile page, looks like this:
<img width="1216" alt="Screen Shot 2021-08-02 at 8 31 13 AM" src="https://user-images.githubusercontent.com/12800484/127862700-b8cdea90-95c0-4746-8160-2e2544e97d50.png">

@kaatvds - should the "invite Users .." be moved under "Edit Community Info", "Add/Remove Administrators" ?

**Comment by kaatvds** [comment]
I think that's a good placing.
Kaat

**Comment by BradHN1** [comment]
Further testing:  Import page looks as follows:
<img width="1233" alt="Screen Shot 2021-08-02 at 9 01 17 AM" src="https://user-images.githubusercontent.com/12800484/127866192-a5a4e6de-a8e4-41d4-9f5b-546ec21f5352.png">

A few issues:
1.  title update to "Import Users via CSV Upload"
2. a little hard to read the text on the blue background
3. Can "Choose File" button or drag and drop; this isn't really clear
4. The personalize text box could be HTML, and needs to be larger
5. The team pull down should only have teams from the community in question
6. When I hit Submit, nothing happened (will investigate later)

**Comment by BradHN1** [comment]
Improve the instructions to make csv format clear

**Comment by Davidjwkinghorn** [comment]
A few thoughts for improvements for this page:

1. I like that there is some flexibility of how CSV files can be formatted. This should be communicated before a file is selected.
2. File selection should only need to happen once.
3. Some of my valid email addresses came up as invalid. If I had to guess here, some characters that should be valid aren't allowed. e.g. "+". *
4. The formatting of the submit button should match the formatting of the same buttons on other forms. The grey color of the button almost makes it look like it's disabled.
5. Some more feedback is needed upon hitting submit. Success message, error message etc.

* I like to use variations of my own email address for testing so others don't receive automated emails. Using the "+" symbol allows me to create these variations so they're still unique for the database, but all send to the same place so I can be sure the automated emails still work. my.email+1@address.com, my.email+2@address.com, and my.email+3@address.com all still send email to my.email@address.com. Some users also like to use this to figure out who is sharing their information when they receive spam.
