### ISSUE TITLE
Admin portal hangs with blank screen on create or edit community

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#389]
Blank screen in admin create community.  Errors in javascript console:
<img width="1080" alt="Screen Shot 2021-09-10 at 4 17 32 PM" src="https://user-images.githubusercontent.com/12800484/132912926-cc295602-04e1-42dc-bce0-a9893579bbf7.png">

**Comment by nenadev21** [comment]
I didn't get the blank screen. 
However, when submitting a new community or editing an existing one, I got a red toaster saying that I had an error under the subdomain. I tried the options provided but they didn't work, so I couldn't save edits or add a new community. I was using a super admin account 

<img width="1440" alt="Screen Shot 2021-10-05 at 7 01 53 PM" src="https://user-images.githubusercontent.com/69801600/136115271-156743be-2eff-4b94-a6f4-5a339fc0b1b7.png">
<img width="1440" alt="Screen Shot 2021-10-05 at 7 09 00 PM" src="https://user-images.githubusercontent.com/69801600/136115309-066c04e8-53b5-47a7-8994-8b8a0efe259f.png">
