### ISSUE TITLE
All Rich Text boxes broken!

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#391]
In admin portal, try to type into a rich text box and it clears imnediatly and acts crazy.

**Comment by BradHN1** [comment]
@frimpongopoku - I've found the fix for this.  Two things:

1. value was being passed into TinyMCE as a function, and it needs to be a string.  Error in console:
![Screen Shot 2021-09-13 at 8 52 46 AM](https://user-images.githubusercontent.com/12800484/134156188-8cd8aa3b-4597-4ffb-8135-fa81a8a14af7.png)

2. We were setting initialValue and value.  according to https://stackoverflow.com/questions/66780848/tinymce-input-being-written-in-reverse-order, this can cause the data to be reset.  I eliminated passing initialValue and it works

**Comment by frimpongopoku** [comment]
So you mean the editor was not working for you locally before you made the changes?
