### ISSUE TITLE
On Canary Admin Event Create/Edit - Choosing Date/Time Causes Blank Page on Safari

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-admin#401]
MacOS version 11.6
Safari version 15.0

**Comment by Davidjwkinghorn** [comment]
https://user-images.githubusercontent.com/15150372/134550092-ce59ded9-4759-4b07-bc14-eb8cfd0ab86f.mov

**Comment by BradHN1** [comment]
This was from a package inconsistancy:  reverting to @date-io/moment@1.3.13

**Comment by nenadev21** [comment]
Passed. I didn't get the blank page when selecting the start/end date. Tested both in chrome and safari
