### ISSUE TITLE
End date set for recurring events isn't saving.

### ISSUE THREAD

**Issue by nenadev21** [massenergize/frontend-admin#422]
Steps: 
- Create a new recurring event
- Set start date to 10/6
- Set end date to 10/27
- Make the event recurring for every Wednesday - weekly
- Save changes
- Review event. End date is now set to 10/6 instead of 10/27. Looks like end date wasn't saved

**Comment by BradHN1** [comment]
Correct - except the end date is saved, you just can’t see it.  I added a final_date field within the JSON field for recurring_details, but didn’t make a field specifically for entering that.  I will fix that and make it more clear how it works.

**Comment by BradHN1** [comment]
This should now be fixed.  I added a field for final_date for recurring events.
