### ISSUE TITLE
Time for messages sent to cadmins is displayed in UCT.

### ISSUE THREAD

**Issue by nenadev21** [massenergize/frontend-admin#432]
This could create confusion. Ideally this takes the time of the sender. Another option would be to hide the time and only show the date
<img width="1440" alt="Screen Shot 2021-10-05 at 6 34 05 PM" src="https://user-images.githubusercontent.com/69801600/136112010-bcb0f6e0-9ed4-4f73-ba94-fc52c1212902.png">

**Comment by frimpongopoku** [comment]
This is not a problem anymore



![Image](https://user-images.githubusercontent.com/26961591/171603390-99076c22-e0fe-4628-b58f-d256ab904a2b.png)
