### ISSUE TITLE
CAN - Single events: If the start date and end date don't match, the time of the event won't be displayed

### ISSUE THREAD

**Issue by nenadev21** [massenergize/frontend-admin#438]
Currently, if those two dates don't match, the time of the event isn't displayed on the user's end
Example: 
<img width="1440" alt="Screen Shot 2021-10-13 at 4 43 27 PM" src="https://user-images.githubusercontent.com/69801600/137210364-574a8b9d-40f1-4172-9bbe-88eeed9866bd.png">
<img width="1440" alt="Screen Shot 2021-10-13 at 4 44 06 PM" src="https://user-images.githubusercontent.com/69801600/137210418-44ad4307-2391-4ac4-8141-afce1941ba41.png">

I believe that in most use cases of a single event, the start and end date of the event will be the same. 
Maybe, we could make that the system take the start date and prefills the end date, so the user only needs to select the end time.

**Comment by Davidjwkinghorn** [comment]
@BradHN1 is this intended to work this way? My assumption is that for multi-day events cadmins could post their own event schedule in the description.
