### ISSUE TITLE
Admin Portal Media Gallery

### ISSUE THREAD

**Issue by frimpongopoku** [massenergize/frontend-admin#457]
Link to problem and solution spec: https://docs.google.com/document/d/1VY43DdrvOzrDN7TFB66ibc065gEOOfXdowp1nuJ6uCg/edit

**Comment by BradHN1** [comment]
This is the same as issue #266 which will be closed.  Kaats comment on that ticket:
Would be SO awesome to have a library of images so cadmins don't have to download images from drive to their computers and then upload them again each time
Would probably also save bandwidth as we wouldn't be uploading the same image over and over.

**Comment by BradHN1** [comment]
This works great, a fantastic addition.  
Here are some comments and suggestions when there s time.:
1.  Why limit descriptive text to 30 characters?  I suggest show first 30 characters and click on it to show the entire text.
2. The descriptive text should be shown when an image is selected. 
3. The dated added or modified should be shown when image is selected, and who submitted it.
4. It should show the image size (pixels and MB) when image is selected
5. It should show an image URL when the image is selected
6. Uploading image: add the ability to crop or resize.
