### ISSUE TITLE
Dev admin site: CORS issue coming from certain API requests

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#468]
@dim505 experienced the following error, trying to edit content on the dev admin portal:

![image (4)](https://user-images.githubusercontent.com/12800484/143094948-f0db7b6c-cc26-4559-a371-02881df3f038.png)

It seems that the call to vendors.listForCommunityAdmin relates to the problem.  May be an API issue

**Comment by Davidjwkinghorn** [comment]
@BradHN1 Has this been resolved?
