### ISSUE TITLE
No way to enter a team admin

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#47]
ISSUE 1050
Reported on Tue Nov 19 2019 15:47:54 GMT-0500 (EST)
Reported by Bradley Hubbard-Nelson(brad@massenergize.org)
PRIORITY = High
STATUS = Feedback - Submitted 

Site Url: http://admin-dev.massenergize.org/admin/edit/37/team

Description:
  (workaround in Django admin); when creating a team on Cadmin, it does not ask for team admin email and name and I think we need that when we want to show users a button to contact the team leader and the CAdmin needs this info; and we want to be able to download/export list of teems, their admin and relevant contact info

User Role: Super Admin
Notes: if easy fix please fix, if not, defer (cf. Slack)

**Comment by BradHN1** [comment]
Admin portal has a way to do this now, but it doesn't work properly.
I was signed into admin-dev as brad@massenergize.org (sadmin), and tried to change the user hubbardnelson@gmail.com to be an admin of "Cool People" team.  See following figure:

![Screen Shot 2020-02-18 at 11 31 21 AM](https://user-images.githubusercontent.com/12800484/74756263-46f4f800-5242-11ea-80d1-76c26a270825.png)

When i submitted the change, it added brad@massenergize.org as an admin for the team, but left hubbardnelson@gmail.com as a regular member:

![Screen Shot 2020-02-18 at 11 34 11 AM](https://user-images.githubusercontent.com/12800484/74756557-bd91f580-5242-11ea-9416-44162b7a5427.png)

**Comment by kaatvds** [comment]
This issue is actualy critical because when someone clicks contact admin in team leader board, annd send a message, it says "your message we sent successfully" but there is nowhere on the S/Cadmin side where this message is visible. Also, Under C/Sadmin that Team admin and the Community  admin message are the same list.

**Comment by kaatvds** [comment]
am reopening because we CAN put in  team admins and message is "sent successfully" but as  Cadmin can't see that message: it is not sent to my email or to the Team message board on Cadmin. So someone may be leaving messages but Im not seeing them :(
