### ISSUE TITLE
Add administrators for community

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#495]
When we added Jazz as admin for a community, her profile wasn't added to the community admin group

**Comment by mattia-danese** [comment]
Creating a new `community` and adding an existing `user profile` as the admin successfully creates a `community admin group` for the `community` and adds the `user profile` to the `community admin group`. 

Prior to doing the above, the `user profile` was not a Cadmin and did not belong to any communities. After doing the above, the `user profile` did not change, it is not reflected that they are now a Cadmin and belong to a community.

**Comment by mattia-danese** [comment]
Adding and removing `user profile` from existing `community` works correctly, `user profile` and `community admin group` are both updated correctly.

**Comment by mattia-danese** [comment]
This issue was fixed in ticket [#554](https://github.com/massenergize/api/pull/554)

**Comment by BradHN1** [comment]
This is still a bug.  I added hubbardnelson@gmail.com as the primary contact for an existing community, and that profile was converted to be an admin (I think) but not added to the community admin group

**Comment by BradHN1** [comment]
I may have been mistaken; on retesting it worked fine.
