### ISSUE TITLE
Adding users via CSV invite - fails

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#498]
Jazz observed this during testing

**Comment by kaatvds** [comment]
2/14: still fails. 
![image](https://user-images.githubusercontent.com/30277868/153928046-779bb7a3-42d4-4606-bdaf-d03937454aec.png)
![image](https://user-images.githubusercontent.com/30277868/153928096-d590ebf5-91b2-48d9-8946-e11d87e90eb9.png)
