### ISSUE TITLE
Issue with admins, deleting? 

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#523]
This admin persona used to be an admin for Wayland and Demo, but for the purpose of a training Melrose I deleted that persona as an admin from those two. 
Screenshot: On my admin dashboard I only have Melrose as a community. So far so good.
Screenshot: In a testimonial, where linking to action, the dropdown shows me towns I am NOT a cadmin for (anymore).
![image](https://user-images.githubusercontent.com/30277868/157897707-b8c791d3-35cf-4345-b18a-0eba0c184c96.png)
![image](https://user-images.githubusercontent.com/30277868/157897560-cdcffa13-870e-46ba-9dc8-2b72330ef7f9.png)

**Comment by kaatvds** [comment]
Same bug?
logged in as "Kaat from Anytown" under users I only see Melrose users =  corrrect
![image](https://user-images.githubusercontent.com/30277868/157898931-917c2096-ca5e-4a3f-8628-ea01ec6fb8f1.png)
Kaat as superadmin: KaatfromAnytown is listed as admin for all those other communities:
![image](https://user-images.githubusercontent.com/30277868/157899586-cbe35635-f931-4121-ab88-3b18513e49d3.png)

**Comment by BradHN1** [comment]
@kaatvds - this screenshot shows that "Kaat from AnyTown" is a Community Admin, and that profile is a member of 6 communities;  it doesn't mean that profile is a cadmin for each of the 6 communities, perhaps only one.

**Comment by BradHN1** [comment]
I've tried to reproduce the first issue, using my cadmin account bradhn@mindspring.com, and was not able to see actions from communities which I was not the cadmin of in editing testimonials.

**Comment by kaatvds** [comment]
I can't reproduce it either. Under communities in testimonials I now only see the towns I'm an admin for. Closing.
