### ISSUE TITLE
CAN: Text editor box doesn't open on event creation

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#529]
![image](https://user-images.githubusercontent.com/30277868/159024757-75a77435-e110-4dbc-8ca8-02e457f3e585.png)

![image](https://user-images.githubusercontent.com/30277868/159024822-6161fbd3-3a95-4127-b34a-76347f82da16.png)

**Comment by BradHN1** [comment]
@kaatvds I am not seeing this problem.

**Comment by kaatvds** [comment]
I don't see it  now either. Fixed!
