### ISSUE TITLE
Clean up filtering on lists - don't filter on fields that should be searched instead

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#531]
No reason to filter on names, etc.  Search is for that.

Also for now, don't filter on Live/Not live since that isn't working.  Next ticket will address that.

**Comment by kaatvds** [comment]
Not sure if this belongs here or needs a new ticket: Filter for Sadmin on All Users for "Community" gives all kinds of combinations:
![image](https://user-images.githubusercontent.com/30277868/162257881-5b3d3e3d-abdd-445b-b99f-4993e3ab19ab.png)
