### ISSUE TITLE
Fix filtering of Live/Not Live

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#532]
Currently Live/Not live is not filterabe.  See below screen shot:

<img width="527" alt="Screenshot 2022-03-21 at 16 41 24" src="https://user-images.githubusercontent.com/12800484/159288472-c8580113-db01-4491-86d8-45926c04f818.png">

**Comment by frimpongopoku** [comment]
This feature was removed entirely by @BradHN1 , so we can close this ticket @Davidjwkinghorn

**Comment by BradHN1** [comment]
We need to add filtering back on live/not live, and make it work.
