### ISSUE TITLE
Error copying action as SuperAdmin

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#537]
In Prod, as a superadmin, I tried to copy the action "Switch to electric lawn equipment' and the admin portal hung with the following error:
<img width="639" alt="Screen Shot 2022-03-28 at 3 37 03 PM" src="https://user-images.githubusercontent.com/12800484/160473850-3f13dd39-6cd2-47ee-a432-f833a46e8fef.png">

**Comment by BradHN1** [comment]
Tried it again and it seemed to work, though I suspect that was because the action was created the first time.

**Comment by frimpongopoku** [comment]
@Davidjwkinghorn, this is fixed
