### ISSUE TITLE
When click link from email (like a user sent you a message) Admin portal hangs when visiting from window where non-admin profile is active

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#538]
Visiting admin.massenergize.org in a browser window with my hubbardnelson@gmail.com profile active, the screen stays blank.

Javascript console contains the following:
<img width="949" alt="Screen Shot 2022-03-29 at 8 53 38 AM" src="https://user-images.githubusercontent.com/12800484/160615615-363e3a87-9d01-45fb-9dbc-c86c38c3da34.png">

**Comment by frimpongopoku** [comment]
I could not replicate this @BradHN1. When a non-admin profile is active on user portal page and I try to view a message with a direct link on admin, I get redirected nicely back to the admin login page 🤔
