### ISSUE TITLE
Issue with create/delete tag for SAdmins

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-admin#559]
Ellen:
> Note, after I created it and tagged an action with the new tag, I did not see that tag show up on the community/action -- see wayland take a climate class m-- I create a tag called test tag and it is not visible. 

> "Test tag" is a tag collection.  I see the tag "A few" on that action.

> Created test tag but then when I clicked the box and the trash can, I could not delete it

**Comment by BradHN1** [comment]
This was user error
