### ISSUE TITLE
Click link to admin portal in email - go to that page after sign-in

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#567]
Generally if you aren't already signed in tot he admin portal, when you click a link it doesn't take you to the page

**Comment by frimpongopoku** [comment]
@BradHN1  could you please clarify this?

**Comment by Davidjwkinghorn** [comment]
When clicking or pasting a link to the URL bar to a page on the admin portal if you are logged in already it should just take you there. If you are not logged in, the admin portal should redirect you to the original URL after prompting for sign in.
