### ISSUE TITLE
When copying an action, some info does not get copied over

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#571]
namely all the tags

original:
![image](https://user-images.githubusercontent.com/30277868/166247438-fc6bbb1f-1413-4325-8847-bfb9c4aa2dbe.png)

copy:
![image](https://user-images.githubusercontent.com/30277868/166247461-627863b8-7d03-4246-84bb-3b41563da0de.png)

**Comment by frimpongopoku** [comment]
This is fixed in this PR: https://github.com/massenergize/api/pull/541 
And I think the PR is merged, so it should be available after deployment
