### ISSUE TITLE
Prod: clicking unlive on "live?" button in ALL lists archives  them > disappear 

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#572]
When clicking the live/not live button in EVENTS, ACTIONS and TESTIMONIALS, unliving archives the item > neither admin nor supaeradmin can see it. 

Sorry, making this "critical" as I'm fielding lots of questions and requests to get those back.

**Comment by Davidjwkinghorn** [comment]
We also need to go through and unarchive items that were unintentionally archived.

**Comment by frimpongopoku** [comment]
"agachew" 🤣 🤣 

> @frimpongopoku are you able to look into this as a top priority?

**Comment by frimpongopoku** [comment]
This is also fixed @Davidjwkinghorn
