### ISSUE TITLE
Add Team Admin name & email to Teams data download

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-admin#585]
**User Story.**

As a CAdmin, I want to be able to quickly download and contact my team admins. So that I can rapidly reply to prompt team action or get in touch with team admins to alert for any number of actions.

Current data Teams data downloads are available on the bottom of the community page and the Teams page.

RELATED change: on All Teams page, add a column to display Team Admin name.

Assigned priority 1 because this is impeding good use of Teams functions. Ticket request originated with Ellen Tohn.

**Comment by BradHN1** [comment]
This is supposed to be added to the API data download., and have a column on the all teams page.
