### ISSUE TITLE
admin list of events can we see what is live or not

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#59]
ISSUE 1136
Reported on Fri Dec 06 2019 14:59:43 GMT-0500 (EST)
Reported by MassEnergize(KAATvds@gmail.com)
PRIORITY = Medium
STATUS =  - Submitted 

Site Url: http://admin-dev.massenergize.org/admin/read/events

Description:
in admin list of events: can we see what is live or not?

User Role: Community Admin

**Comment by ellentohn** [comment]
This looks to be the same as issue #99, see my comments on that issue.  I can filter under Live -- (All/No) Can we add a "Yes" option so that we can filter as (All/Yes/No).
