### ISSUE TITLE
Events page - click "Live/Not Live" - reverts to previous filter criteria

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#596]
**Describe the bug**
When I click on the Live/Unlive chip on the events page (or other pages ?) it causes the filter that i had set to go to the previous setting

**To Reproduce**
1. Go to all events page
2. Change filter to pick a single community
3. Pick an event and set it to be live, or not live
4. See that the filter criteria have changed, other community events are shown

**Expected behavior**
The filter criteria shouldn't change when yhou click this.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Davidjwkinghorn** [comment]
I think this has been done already. Needs verification.

**Comment by mattia-danese** [comment]
Tested all relevant pages and filter no longer changes

**Comment by abdullai-t** [comment]
This works
