### ISSUE TITLE
Deleting a Team didn't work

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#597]
**Describe the bug**
Deleting a team from the all teams page didn't remove the team

**To Reproduce**
1. Go to all teams page
2. Click on the box to select a team
3. Click the trash can
4. See that the team still remains in the list

**Expected behavior**
THe team should disappear from  the list

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abdullai-t** [comment]
This issue has been fixed. here are demos from safari and chrome
https://user-images.githubusercontent.com/42780120/173934008-0e084d8f-3163-4882-b184-61d7a815b5f1.mov

https://user-images.githubusercontent.com/42780120/173934209-8f2664d1-ac2f-48be-b480-87a2c6def5dc.mov
