### ISSUE TITLE
CAN - Team shows up twice on Admin Portal teams list

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#598]
**Describe the bug**
during testing I made some changes to share a team between two communities (Cooler Concord and Energize Carlisle) and the team shows up twice in the list now.

<img width="1457" alt="Screen Shot 2022-05-27 at 6 43 52 AM" src="https://user-images.githubusercontent.com/12800484/170685070-a15a3710-acaf-4684-a93b-32365803c6cb.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abdullai-t** [comment]
I think it has been fixed

**Comment by abdullai-t** [comment]
I think it has been fixed

**Comment by abdullai-t** [comment]
I think it has been fixed
