### ISSUE TITLE
All testimonials page - Set testimonial live/not live - Chip state doesn't change

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#599]
**Describe the bug**
All testimonials page - Set testimonial live/not live - Chip state doesn't change

<img width="1467" alt="Screen Shot 2022-05-27 at 6 51 55 AM" src="https://user-images.githubusercontent.com/12800484/170686287-f4bc98d7-1d1a-4597-943f-a42400fd799b.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BradHN1** [comment]
the chip always says no even if the testimonial is set live.

**Comment by frimpongopoku** [comment]
@BradHN1 I dont think this issue exists anymore.  Please check again on your end.
Also See video of my test below

https://user-images.githubusercontent.com/26961591/173529486-90c7cd2f-8777-4a49-b5af-b9b356c36674.mov
