### ISSUE TITLE
[Feature] Make Templates impossible to delete from the Admin portal.

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-admin#608]
**User Story.**
As a **Community Admin** (Actor/User)
I want **templates to be impossible to be deleted** (Goal of the actor/user)
So that **I can't delete it by accident.** (Why/What is the result)

**Additional details/context**
Only Sadmins should be able to delete templates.

As devs we can have some way to delete the master community template if we have to (for whatever reason), but we shouldn't rely solely on a message saying "DO NOT DELETE". We should make it harder at least to delete the Master Template if not outright blocking it somehow.

**Acceptance criteria.**
- [ ] Cadmins are unable to delete any templates.
- [ ] Sadmins and Cadmins are unable to delete the master template community from the admin portal.

**Comment by BradHN1** [comment]
Thsi was not working in dev - @frimpongopoku 
I was able to delete a template as a community admin

**Comment by frimpongopoku** [comment]
> Thsi was not working in dev - @frimpongopoku I was able to delete a template as a community admin

@BradHN1  I think its because PR that is meant to do that is not merged 🤔 (https://github.com/massenergize/frontend-admin/pull/633)  .... or was it pulled into something else?

**Comment by BradHN1** [comment]
You’re right, we figured that out when I met with David. He’ll merge it

**Comment by BradHN1** [comment]
Works fine in canary now
