### ISSUE TITLE
optional community donate link 

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#61]
ISSUE 1149
Reported on Mon Dec 09 2019 13:37:39 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = Medium-Low
STATUS =  - Submitted 

Site Url: http://admin-dev.massenergize.org/admin/edit/80/donate

Description:
On pages > donate > would love to have a  optional paypal link for the community group under "about our community" for those groups that have a bank account and take donations. 

User Role: Community Admin

**Comment by kaatvds** [comment]
Actually, several groups don't have paypal, but other ways of taking donations. So there should be just a generic "donate" button that thn links to paypal or venmo or their own donate page on their website.

**Comment by ellentohn** [comment]
Update on this, 2 actions

1. Enable rich text so communities can put in hyper link for a donation to their organization and also ability to have a hard return.
2. Kaat to provide new image for the Paypal button to clarify that it is a donation to MassEnergize

**Comment by BradHN1** [comment]
Spec out how this would look, run it by community groups including Newton
WYSIWYG editor may be helpful to bring in button image with a link to where they want to go.
Need API change (with model change),

**Comment by kaatvds** [comment]
There is, on the Admin side, a box for a video link  and one for a donate link. None of these are shown. All that is shown is on text box and on big, hard-coded paypal button. 
changes:
1. Make rich text possible. here. Appeals for $$ need to look good.
2. two text boxes and two buttons: First one,  for community to write, with a simple donate button that can lead to paypal or their other site, etc. Second one: for ME with ME paypal button, same size as community's donate button.
3. Would be great to have an embedded video above the first donate button (optional)
4. IF PAYPAL: no have all those credit cards shown under it. Just the Paypal button is fine.
5. 
![Untitled design (9)](https://user-images.githubusercontent.com/30277868/108728208-595ddd80-74f7-11eb-87eb-a31ba90ed45e.jpg)
