### ISSUE TITLE
[Bug] Hang on editing Testimonial

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-admin#616]
**Describe the bug**
Megan reported that clicking to edit a testimonial hangs and she is unable to edit any.

**To Reproduce**
1. Click the pencil on a testimonial on the admin portal
2. Site hangs and never loads

**Comment by frimpongopoku** [comment]
@Davidjwkinghorn  I think we might need more information on how to replicate this: 

Wasnt sure of what platform this was happening on so I tested on live admin dev, and live admin prod, and all is working fine 🤔  

See video: 

https://user-images.githubusercontent.com/26961591/173753132-1355b2ca-03be-4c22-8277-357b6c56b99a.mov

**Comment by Davidjwkinghorn** [comment]
We definitely need more info on this. I wasn't able to reproduce this either.

**Comment by Davidjwkinghorn** [comment]
Could not reproduce
