### ISSUE TITLE
not use one our names e.g. "Ellen Tohn" as example

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#62]
ISSUE 1151
Reported on Mon Dec 09 2019 13:42:24 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = Low
STATUS =  - Submitted 

Site Url: http://admin-dev.massenergize.org/admin/edit/80/community-admins

Description:
not use one our names e.g. "Ellen Tohn" as example, use "Jane Doe" instead

User Role: Community User

**Comment by kaatvds** [comment]
e.g. in create vendor > name and email of onboarding person.

**Comment by kaatvds** [comment]
Ellen's name and email are still used in vendors.
![image](https://user-images.githubusercontent.com/30277868/76422897-54eaf400-637c-11ea-8bdc-a64e113ba14a.png)

**Comment by kaatvds** [comment]
moving it back to In Progress because Ellen's name is still there on vendors.

**Comment by kaatvds** [comment]
![image](https://user-images.githubusercontent.com/30277868/76866440-89f2bd00-683a-11ea-9493-3052a63436b1.png)
