### ISSUE TITLE
Make it impossible for Cadmins to delete Templates

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#624]
Someone deleted all templates but one... Make this impossible for admins. Only superadmins can delete templates.
This until we have  solution for templates, actions sharing, etc.

**Comment by Davidjwkinghorn** [comment]
Duplicate with [Issue 608](https://github.com/massenergize/frontend-admin/issues/608)

**Comment by BradHN1** [comment]
I just deleted a template in dev   There was one called Electricity Use Monitor, and I clicked the box and said "delete" and it is now gone:

![Image](https://user-images.githubusercontent.com/12800484/178304425-a85f7785-3658-4d15-865f-bab5de7948db.png)

as a community admin
