### ISSUE TITLE
Updating Action content - doesn't seem to work - redux issue

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#638]
**Describe the bug**
An action was created, but without the "steps to take" or "deep dive"; when you edit the action again to add them, and then edit it again, they don't appear to be there.  

**To Reproduce**
1. Create an Action, leave Steps to Take blank
2. Edit the action, add Steps to Take, and submit it, which takes you back to the list view 
3. Edit it again, and see that Steps to Take are not there.  (Don't submit, but cancel back or hit back button)
4. Refresh the browser, edit the action again and you'll see the Steps to Take are there.

**Expected behavior**
Evidently the Redux store isn't updated, and when you go to edit an action, the action data comes from the Redux.  This is probably an issue with Events

**Screenshots**
This happens both on Canary and Prod.  
Video:
[screen-capture.webm](https://user-images.githubusercontent.com/12800484/178724489-3a2b9b3f-39ef-439a-b962-479062bf17f6.webm)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by frimpongopoku** [comment]
@BradHN1  

Did you fix this already? Cos It worked on my end: 


https://user-images.githubusercontent.com/26961591/179926642-6cd7f403-4e6c-4f5d-9297-671fe589008f.mov
