### ISSUE TITLE
[Bug] SyntaxError: Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-admin#640]
**Describe the bug**
Makayla was seeing this all over the place in Chrome, but not in Safari. It's critical since it means some admins might not be able to use the portal, though using another browser seems to be a workaround. 

**To Reproduce**
This error message showed up every time Makayla tried to submit new actions, events, or changing content for different pages.

**Expected behavior**
Changes made should take effect and not throw this error message.

**Desktop (please complete the following information):**
 - OS: Mac (May also be an issue on PC)
 - Browser Chrome (Possibly other browsers too)

**Comment by abdullai-t** [comment]
I am unable to replicate the error. Everything seem to work fine

**Comment by abdullai-t** [comment]
I am unable to replicate the error. Everything seem to work fine

**Comment by BradHN1** [comment]
@abdullai-t - it isn't surprising that you can't reproduce the error, but it does happen to users, so we need to catch it, determine the API route and parameters, and report the relevant information.   I am taking a shot at fixing it in the frontend-admin branch JsonFormatError
