### ISSUE TITLE
Media library - cropping isn't implemented?

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#651]
**Describe the bug**
We need to be able to crop pictures with the media library.  This seems to be partially implemented.

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screen Shot 2022-07-22 at 8 02 30 AM](https://user-images.githubusercontent.com/12800484/180435434-093cfdf2-3d3e-48f8-8ea7-7025bee4478a.png)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BradHN1** [comment]
Note other features requested in ticket [457](https://github.com/massenergize/frontend-admin/issues/457) 

1. Why limit descriptive text to 30 characters? I suggest show first 30 characters and click on it to show the entire text
2. The descriptive text should be shown when an image is selected.
3. The dated added or modified should be shown when image is selected, and who submitted it.
4. It should show the image size (pixels and MB) when image is selected
5. It should show an image URL when the image is selected
6. Uploading image: add the ability to crop or resize.
7.

**Comment by frimpongopoku** [comment]
@BradHN1  actually cropping is enabled already 🤔  
Here is a demo. But lemme know if there is any feedback so I an add it to the other suggestions you made here

https://user-images.githubusercontent.com/26961591/181198821-9de12647-929e-4f03-bca6-db482e294041.mov

**Comment by BradHN1** [comment]
There is a tab on the dialog “Crop”.  Since I saw that I thought it was the way cropping was implemented, but I couldn’t figure out how that was supposed to work.

**Comment by Davidjwkinghorn** [comment]
There's a ticket for cropping already in the sprint backlog: [Issue 288](https://github.com/massenergize/frontend-admin/issues/288). There was discussion of resizing images rather than cropping.
