### ISSUE TITLE
Edit Home Page w Media Library - wrong picture shows up

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#653]
**Describe the bug**
In Canary testing, I changed one of the pictures from the media library, and the one I picked in the media library was not the one that showed up on the home page.  See figures below

**To Reproduce**
1. Go to Community Profile for Cooler Concord on Canary
2. Remove the first image
3. Click on Select homepage images
4. Choose a new image and save the homepage settings
5. Go to community site and refresh homepage

**Expected behavior**

**Screenshots**
![Screen Shot 2022-07-24 at 6 27 53 AM](https://user-images.githubusercontent.com/12800484/180643061-a7957a50-880e-4258-a7dc-a792592698a6.png)
![Screen Shot 2022-07-24 at 6 27 37 AM](https://user-images.githubusercontent.com/12800484/180643060-42db0c11-cce8-4ec7-8410-51dc4d2f1ff3.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by frimpongopoku** [comment]
I dont think this still happens anymore

**Comment by Davidjwkinghorn** [comment]
If this no longer occurs I'll close it out. We can always open new issues if it comes back.
