### ISSUE TITLE
Create/Update community - don't allow subdomains to have spaces

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#656]
**Describe the bug**
It doesn't work for a subdomain to have a space - don't allow it on the admin portal, and make instructions clear

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screen Shot 2022-07-24 at 7 26 21 AM](https://user-images.githubusercontent.com/12800484/180644850-1f1b8e4a-09d2-4b59-a191-06993ad83889.png)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Davidjwkinghorn** [comment]
We can either disallow spaces or we could replace all spaces with underscore characters.

**Comment by mattia-danese** [comment]
I think underscores would be best, very legible and still allows for multi-word names
