### ISSUE TITLE
PROD - Error updating vendor

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#659]
**Describe the bug**
I tried to update the logo for a vendor whose logo had been replaced by the wrong graphic (Admin issue 658)
Failed with error message shown below.

**To Reproduce**
1. Go to Vendors list
2. Edit the Black Earth Compost vendor
3. Upload a new image file
4. Submit and see error

**Expected behavior**

**Screenshots**
<img width="667" alt="Screen Shot 2022-07-25 at 1 44 06 PM" src="https://user-images.githubusercontent.com/12800484/180842563-bcf3f9fe-db48-475b-af3f-5c65bc0bc5f2.png">
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by frimpongopoku** [comment]
@BradHN1  I tested on prod, canary, and dev, but still cldnt replicate this 🤔 . I tried with black earth compost itself, and some other random vendors that arent live, but it was working fine. 


Uploading Screen Recording 2022-07-27 at 09.45.30.mov…
