### ISSUE TITLE
Media library, assigns picture to wrong community

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#660]
**Describe the bug**
As a superadmin I am trying to fix an image.  It thinks I am doing it for the Sustainable Middlesex Community

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1033" alt="Screen Shot 2022-07-25 at 1 43 02 PM" src="https://user-images.githubusercontent.com/12800484/180843151-34dba3f1-9d1d-4588-8abe-181564199c3b.png">
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BradHN1** [comment]
As a superadmin I need to be able to see pictures from all communities.

**Comment by frimpongopoku** [comment]
> As a superadmin I need to be able to see pictures from all communities.

@BradHN1  should this be a different ticket ?
