### ISSUE TITLE
[Feature] Record user name for admin who creates/updates an action, event, etc

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#664]
**User Story.**
As an admin I want to know who created an action or other content, because it is relevant

**Additional details/context**
We should pass the user for recording who created content to the tables who can store it.

**Value added.**
What do you think the value of adding this feature is? Help managers and developers know how this should be prioritized.

**Acceptance criteria.**
The conditions that must be met for this to be done. For example, for a login feature: User is securely and reliably logged in until timeout or manual sign-out.

**Comment by Davidjwkinghorn** [comment]
This should also be done ahead of allowing community portal users to submit actions, events, and Service providers. There needs to be traceability of content to the one creating it. I think we also need a way for users to report content to community admins in case of harassment etc.

**Comment by frimpongopoku** [comment]
@BradHN1  this is the ticket.


And the PRs are here: https://github.com/massenergize/frontend-admin/pull/706 
https://github.com/massenergize/api/pull/581

**Comment by frimpongopoku** [comment]
Ooo I see, right now it doesnt. But I can make that change a different PR,
cos it seems easier to go over and merge.
 Then we can take our time to vet the bulky version well before adding that
also.

**Comment by frimpongopoku** [comment]
@BradHN1  just checked. It looks like 

> @frimpongopoku - The original intention of this ticket was to simply fill in the "user" field which was added to the models Action, Event and Vendor. What you've done is much more comprehensive. Does it also fill in the user fields?


@BradHN1  just checked. You already implemented this in Action, Vendor, and Event as you described here. And it looks like you did it 6 months ago 🤣 🤣 .
