### ISSUE TITLE
[Feature] Media library - add "Service Provider" as content type, and more

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#665]
**User Story.**
As an admin 
I want view media in the media library from service providers, and from community pages (home, about us, etc)

**Additional details/context**
Media gallery can fllter and show content related to several things, but not service providers or images on community pages:

<img width="1461" alt="Screen Shot 2022-07-28 at 11 25 30 AM" src="https://user-images.githubusercontent.com/12800484/181577362-1516365a-7daa-4527-bc02-f8f2841bd6e6.png">

I also want to be able to select pictures added by particular users, however for most pictures this info isn't being saved.

**Comment by frimpongopoku** [comment]
About the service providers... We want to be allow users to reuse service provider logos...? 🤔 
Cos service providers only upload their logos and nothing else isnt it? 🤔

**Comment by Davidjwkinghorn** [comment]
I think the use case for this is that certain actions, events, etc might relate to specific service providers. So being able to quickly find the logo of a certain service provider could be useful.
