### ISSUE TITLE
[Feature] Inter-community browsing - List filter - Select communities to show content from in admin portal lists

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#671]
**User Story.**
As a community admin
I want to choose whether to view content from other communities or only my own
So that I can copy content for my community

**Additional details/context**
For community admins, the admin portal lists currently show content from their community and template content.  This makes the API call not take too long.  But this prevents sharing content from other communities.  We need a way to select communities, ideally including the following options:
* just my community(s)  - default
* include communities within a geographic distance
* select particular communities which you want to include

This would likely require API changes as well as admin portal changes.

**Value added.**
What do you think the value of adding this feature is? Help managers and developers know how this should be prioritized.

**Acceptance criteria.**
The conditions that must be met for this to be done. For example, for a login feature: User is securely and reliably logged in until timeout or manual sign-out.

**Comment by BradHN1** [comment]
For super admins, the admin portal lists (for example, All Actions) makes an API call which returns the content for all communities, but for community admins, the API call just returns the content for those communities the person is an admin of (and also the template content).  Community admins also would like to see content from other communities so that they can copy it for their community.  

A few months back, the API calls like actions.listForCommunityAdmin were changed to add an optional community_id argument, where if this is 0, they would return the content from all communities.  I tested this with the admin portal and made it so template content and content from other communities is not modifiable.  However, the concern was that these calls might be slow.  (@frimpongopoku was especially concerned, since his internet is slow, so he proposed to make the content returned from the API in pages (issue #480 )).  In any case we should not necessarily return all content all the time because it will be slow for some cadmins.

What this ticket proposes is a way of filtering on the call to the backend, so that instead of returning all communities, it returns content from a selected set.  Currently the filtering is done in the front-end, and the UI requires you to select particular communities, like in this screenshot (from a superadmin):
<img width="1421" alt="Screen Shot 2022-08-15 at 9 04 51 PM" src="https://user-images.githubusercontent.com/12800484/184771258-3c8f4b7d-9aef-4211-ac93-20eeb57631f4.png">

This long list of communities is less workable as we get more and more; we would need to be able to search and include particular communities, or have a way to select communities within a certain distance from selected communities.  Then the back end API would need to modified to take the list of communities and perhaps a distance parameter to decide which communities content to return.  So this ticket would require front and back-end changes.  

Best way to proceed would be a mock-up of the UI to show how communities would be selected, including filtering by a distance, and write an API ticket for what changes would be needed on the back end to support it.

**Comment by abdullai-t** [comment]
@BradHN1 here is a mockup of how communities would be selected. 

<img width="830" alt="Screenshot 2022-08-18 at 1 24 35 AM" src="https://user-images.githubusercontent.com/42780120/185272124-2ca89e77-2140-4d8b-8c69-2bf5f67d8784.png">

**Comment by abdullai-t** [comment]
@BradHN1 - should I start a work on the pagination

**Comment by BradHN1** [comment]
Yes, that would be good.  Can you start by specifying how the API routes - starting with actions.list, will handle pagination, search and sort parameters, as well as communities?

**Comment by Davidjwkinghorn** [comment]
We will be rolling out the ability for events to made "closed" by the event creator in [this ticket](https://github.com/massenergize/frontend-admin/issues/730). Open events should show up in this filter, but not closed events.
