### ISSUE TITLE
[Bug] Many Divs on action causing huge spacing issue

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-admin#681]
**Describe the bug**
[This action](https://community.massenergize.org/BoxboroughMA/actions/2481) on Boxborough had tons of extra space at the top and bottom of the tab. The extra space appears to be caused by Divs possibly added on the action's creation. 

**Expected behavior**
All actions should display correctly and as intended by the community admin creator.

**Screenshots**
![Screen Shot 2022-08-15 at 9 27 10 AM](https://user-images.githubusercontent.com/15150372/184647827-e52992b0-62a5-4085-884b-a8feb9d101fe.png)

**Comment by BradHN1** [comment]
I'm not sure how to figure this one out, but I did see one odd thing in the admin portal which could be a clue:
<img width="1403" alt="Screen Shot 2022-08-24 at 4 19 58 PM" src="https://user-images.githubusercontent.com/12800484/186515814-9c623d9a-f99d-4d2f-9e2a-4aba2b68dac6.png">

At the bottom of the box it says DIV >> DIV >> DIV >> .... which I think is what is causing the space, though I don't know how to get rid of it.
