### ISSUE TITLE
Link to admin portal page if not signed in gives infinite spinner

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#694]
**Describe the bug**
Following a link to the admin portal gives an infinite spinner, if not signed in

**To Reproduce**
1. make sure you are signed out in the browser window, or an incognito window
2.Go to https://admin-canary.massenergize.org/admin/edit/2967/action
3. Wait - See error

**Expected behavior**
It should lead you to the sign-in page, then once signed in tak you to the correct page

**Screenshots**
<img width="1109" alt="Screen Shot 2022-08-27 at 7 24 57 AM" src="https://user-images.githubusercontent.com/12800484/187028562-542c2662-c349-4e22-b585-e52cb5b2f3b1.png">

**Comment by Davidjwkinghorn** [comment]
I have observed this bug as well. It seems like it's not all urls, but happens specifically when you use a link to a specific action, event, etc.

**Comment by Davidjwkinghorn** [comment]
This should have already been resolved.
