### ISSUE TITLE
testimonials and vendors

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#70]
ISSUE 1188
Reported on Fri Dec 13 2019 18:52:37 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = Medium-High
STATUS =  - Submitted 

Site Url: http://admin-dev.massenergize.org/admin/edit/125/testimonial

Description:
when someone enters a testimonial on the vendor page, it is not clear to the Cadmin on the Cadmin page on testimonials which vendor that testimonial was about. If the user just wrote 'I LOVED this vendors they were great" but doesn't i the body say which company they're raving about, how will the Cadmin be able to tag the right vendor?

User Role: Community Admin

**Comment by kaatvds** [comment]
was solved with"other" option
