### ISSUE TITLE
Admin portal should only ping the API every 3 minutes, not 2 seconds

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#700]
**Describe the bug**
In Application.js, for testing it pings the admin portal every 2 seconds to see if the user is still signed in.  Make it 3 minutes, as intended.  (Could change it to be 1 minute but 2 seconds is a lot of pinging.

**Comment by frimpongopoku** [comment]
Brad already removed this. I should have removed the two seconds after testing. Sorry 🙏
