### ISSUE TITLE
[Feature] Media Library - Tags

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-admin#711]
**User Story.**
As a cadmin (Actor/User)
I want to add tags to images when I upload them (Goal of the actor/user)
So that I or others can filter or search for images I've tagged. (Why/What is the result)

**Additional details/context**
Admins should be able to add tags when uploading new images and edit existing tags on already uploaded images. All images should require at least one tag to make them more easily searchable/sortable. Tags can be the same as those that appear on actions, events, and testimonials. This way an admin can use the same set of images for a certain topic, like solar for instance, across actions, events, and testimonials. This should leverage our existing tags in the models.

**Value added.**
This will make it significantly more easy to find certain images a user is looking for.

**Acceptance criteria.**
Cadmins are able to leave tags on newly uploaded images. These tags are then associated with those images and this info is stored in the database.

**Comment by frimpongopoku** [comment]
the The merge to dev for the PR I made for this somehow didnt retain the changes @Davidjwkinghorn I tnk someone overwrote my changes when there conflicts so I made a new PR, chexk again @Davidjwkinghorn

**Comment by Davidjwkinghorn** [comment]
> the The merge to dev for the PR I made for this somehow didnt retain the changes @Davidjwkinghorn I tnk someone overwrote my changes when there conflicts so I made a new PR, chexk again @Davidjwkinghorn
> 
> Here #756

Must have been one of the times dev got merged into the branch. No conflicts were raised.
