### ISSUE TITLE
[Feature] Media Library - Searching, Filtering, and sorting

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-admin#712]
**User Story.**
As a cadmin (Actor/User)
I want to be able to search existing media by name and tags (Goal of the actor/user)
So that I can find the media I'm looking for quickly (Why/What is the result)

**Additional details/context**
[Issue 711](https://github.com/massenergize/frontend-admin/issues/711) is a prerequisite to this issue for tags. Searching should involve a text field that can match media name and whatever tags are associated with the media. Filtering is also something we should provide. As a first iteration we can start with a simple dropdown of category tags. We should also provide a way to sort media by various factors shown below. 

***Searching***

- [ ] Matching name and/or tags/description

***Filtering***

- [ ] Category tags

***Sorting***

- [ ] By date added, ascending and descending
- [ ] Alphabetical by name and reverse alphabetical

**Value added.**
This will allow admins to find the media they're looking for more quickly and easily.

**Acceptance criteria.**
Searching for a key word should bring up accurate results and filtering by tag should only

**Comment by frimpongopoku** [comment]
* If we are going to want to do different types of sorting with provided image names and descriptions, does it mean we should make image descriptions compulsory when uploading in the gallery...? Cos otherwise the sorting part wont make a lot of sense, and will not really do much....

**Comment by Davidjwkinghorn** [comment]
I suppose sorting by image name might not be too useful. We should still sort by date/time uploaded. I agree with Brad that images should not just show up in an arbitrary order. For searching I'm assuming that all images already have names, even if it's just a filename. We don't need to enforce a meaningful name/filename or descriptions for this since there's no loss for admins who don't provide useful names/descriptions (other than not being able to search for them), but for admins who do so it'll be useful.
