### ISSUE TITLE
[Feature] Add event start date/time to event list view and support sorting by date/time.

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-admin#736]
**User Story.**
As an admin (Actor/User)
I want the events list view to show the time and date of the event. (Goal of the actor/user)
So that so I can sort by date/time and find events by when they are. (Why/What is the result)

**Comment by frimpongopoku** [comment]
@Davidjwkinghorn  this exists already. The "Date" field there is the start date of the events 
<img width="1531" alt="Screenshot 2022-10-12 at 11 24 58" src="https://user-images.githubusercontent.com/26961591/195277231-c4322353-a71d-41bc-bad3-05d7244c3792.png">

**Comment by Davidjwkinghorn** [comment]
I can't remember the circumstances around the creation of this ticket. I think someone requested it, but you're right. It's there.
