### ISSUE TITLE
[Feature] Creating a community - Require selection for Geographically focused communities.

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-admin#744]
**User Story.**
As a sadmin (Actor/User)
I want geographic community to be a required field. (Goal of the actor/user)
So that I don't post a geographically focused community without a geographic area. (Why/What is the result)

**Additional details/context**
If yes selected for "is this community Geographically focused?" Require a selection from the "geographic community" selection for form submission.

**Comment by frimpongopoku** [comment]
@Davidjwkinghorn  is this the part we are supposed to make required? 
<img width="1098" alt="Screenshot 2022-10-13 at 12 11 47" src="https://user-images.githubusercontent.com/26961591/195540637-49156baf-e1e7-4132-8765-a9c69f234115.png">

**Comment by Davidjwkinghorn** [comment]
Yes @frimpongopoku. If Geographically focused is selected the admin must select "Type of geographic community" and provide the appropriate info in the text-box. The problem with what we have now is that sometimes when a community is created "Geographically focused" is selected, but no zip codes or other info is provided and this causes problems that super admins have to manually resolve.

**Comment by Davidjwkinghorn** [comment]
Also, I want to apologize for not seeing many of these comments sooner, my GitHub notifications are screwed up so I don't usually see comments on issues unless I actively look for them. I'm working on getting my settings fixed so I can see recent updates.

**Comment by BradHN1** [comment]
If this wasn't fixed, I'd like someone to demonstrate what the problem is. It seems to require the text field filled in.

**Comment by Davidjwkinghorn** [comment]
> If this wasn't fixed, I'd like someone to demonstrate what the problem is. It seems to require the text field filled in.

I believe Kaat asked me to make this ticket. The problem is that some communities were getting created, set to geographic, but no location was provided. Super admins would then have to manually fix this. @kaatvds may be able to explain this better than I can.
