### ISSUE TITLE
[Feature] Show an event from from another community on my community (and from an email link too)

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-admin#745]
**User Story.**
As a cadmin (Actor/User)
I want to be able to show an event from another community on my community page from a link. (Goal of the actor/user)
So that I can easily show other community's events on my community site. (Why/What is the result)

**Additional details/context**
These links will primarily be used in our report email nudges. A button will be next to each event in that email to show the event on your community. The admin may have to log in first, but they should be rerouted back to a new view showing the other community's event info with an option to show the event on the admin's own community. The event info should not be editable if it's not from the same community that the current cadmin is an admin of. To undo this, the admin should be able to remove the event from their community without deleting it from the creator's community.

When an event from another community (the host community) is shown on an admin's own community (guest community) that event shows up on the frontend-portal with the other events for guest community, but with the name of the host community on the event. The event displayed on the guest community should be the same event object (same ID) as the one from the host community so that RSVPs can be managed by the host community admins.

This can also tie in with [Issue 671](https://github.com/massenergize/frontend-admin/issues/671). This is what happens when you click edit on an event from another community. 
 
**Acceptance criteria.**
Events should be able to be shown on other community sites as described above.

**Comment by Davidjwkinghorn** [comment]
Hi @frimpongopoku, thanks for picking this ticket up! We've made some changes to this feature after some problems with the original idea came up in a meeting today. Instead of allowing admins to duplicate events from other communities, we're basically sharing the same event object so that the original creator of the event can still manage RSVPs.

**Comment by frimpongopoku** [comment]
@Davidjwkinghorn  since @abdullai-t  is tagged in most of the tickets that work with this, I will just assign him to this one as well.

**Comment by Davidjwkinghorn** [comment]
One thing that I need to add is that admins should not be able to share their own event on their own community. Kind of obvious, but it's a detail that should not be left out of the spec. The option to show an event from another community shouldn't show up if the event is in the current admin's own community. 

This makes me realize, for cases where a cadmin is an admin for multiple communities they need to be able to choose which communities to show the event on. Could this be a dropdown to select multiple communities? The dropdown would be populated with all the communities the current cadmin is an admin for.

**Comment by frimpongopoku** [comment]
Yes @Davidjwkinghorn thats a good plan 👍

**Comment by kaatvds** [comment]
Sorry, reopening this issue. I just got the admin event nudge and the events are ordered in a weird way. Please order them from closest to date of sending to later.
<img width="664" alt="Screenshot 2023-03-20 at 2 05 20 PM" src="https://user-images.githubusercontent.com/30277868/226428279-5d0e7f5a-451f-4eda-8496-d56e4d992b62.png">

**Comment by frimpongopoku** [comment]
Since this has become an admin nudge issue, I will tag @abdullai-t  who is already working on that.

**Comment by kaatvds** [comment]
This ticket should be closed.
