### ISSUE TITLE
[Feature] Annual terms of use renewal for admins.

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-admin#752]
**User Story.**
As a community admin (Actor/User)
I want to have to agree to ME legal terms annually to continue be an admin. (Goal of the actor/user)
So that If I don't agree or are not active as an admin, I won't get pelted by nudges and won't have access to the admin portal. (Why/What is the result)

**Additional details/context**
On a certain date every year admins will have to agree to our legal terms before being allowed to sign in. We can give them the option to agree ahead of time at their convenience somewhere on the admin portal and via a link in a nudge.

**Value added.**
What do you think the value of adding this feature is? Help managers and developers know how this should be prioritized.

**Acceptance criteria.**
The conditions that must be met for this to be done. For example, for a login feature: User is securely and reliably logged in until timeout or manual sign-out.

**Comment by kaatvds** [comment]
speccing this out collaboratively[ in this doc](https://docs.google.com/document/d/1hggx_5QWiZ0Avui-4AMj9uykjvmkd8PHjHz_TBGR1Ls/edit)

**Comment by kaatvds** [comment]
feedback on ticket so far (demoed in Slack channel).

- PUT BEHIND FF to roll out
- Postmark emails to admins (of communities not under flag) when feature is introduced and reminders (cf spec doc)?

- from demo looks like when they sign into admin and haven’t signed the MOU: they enter their login and it takes them straight to the MOU page? This is confusing. Take them there but also add pop up (as in specs). TEXT:

Dear Admin,
Once a year, all admins must read and accept the MassEnergize Admin Memorandum of Understanding ("MOU") as a requirement for being a community admin. By accepting the MOU you promise to comply with MassEnergize’s promise to platform users - your community members - of certain assurances (for instance, that their personal information is not sold, that relationships with recommended vendors are transparent, that you use content, like photographs, that you have explicit permission to use, etc). All these assurances are laid out in our[ Terms of Service](https://drive.google.com/file/d/1SP9Jq7WQON6_bsexsmmqkATtcG7vM9R5/view?usp=share_link) and[ Privacy Policy](https://drive.google.com/file/d/14Q_DfQ-5hZlPLz7ox7Gg1Mr0AM_KOHAq/view?usp=share_link). [these links go to the policies on the platform]
Please follow the instructions on this page. It should not take long. 
You will be asked to renew this MOU in a year's time.
If you have any questions, feel free to reach out to [support@massenergize.org](mailto:support@massenergize.org).

- Please use actual MOU: show whole MOU on page (the way you have it) with all under point E bolded so it stands out
- In the MOU text links to ToS and PP 
- Add a download button

- ACCEPT  process = good

- DEFER process looks good but in box 
Add some text re “reach out” in "are you sure" box, to the text, add TEXT:

Please reach out to support@MassEnergize.org if you have questions. Deferring will not affect your user account and you will still be able to use your community’s portal.

- DECLINE: To "are you sure you want to" box, change TEXT to:

You will be signed out and will no longer be an admin. This will not delete your user account and you will still be able to use your community’s portal. 

We want some changes to the emails too. Will get back to you on those soon.
