### ISSUE TITLE
emails of senders of messages

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#76]
ISSUE 1224
Reported on Sat Dec 28 2019 20:47:46 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = 
STATUS =  - Submitted 

Site Url: http://admin.massenergize.org/admin/read/community_admin_messages

Description:
In contact form senders are now asked to leave their emails. But they don't show up in the list of messages in the Cadmin or in the more info on each indiv message (after clicking the triangle)...

User Role: Community Admin
Notes: 1 related to #1248

**Comment by kaatvds** [comment]
We talked about this at our Sprint call. Admin gets no email address when I send a message when I am logged out AND I use an email address that is not the address of a member:
![image](https://user-images.githubusercontent.com/30277868/74061024-28c50780-49b9-11ea-98b5-92c8539e31ee.png)
A you can see the Cadmin form for responding ("TO" field) does not autopopulate, and email does not appear up top (as it does when  the email is that of a user).
