### ISSUE TITLE
when uploading an image specifying communities, I lose the action/event etc I was working on

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#769]
**Describe the bug**
I am creating an action
at end, I click to  upload an image 
at top there is n invitation to upload it for specific communities,
when I click on that, it opens in SAME tab. I go through the motions there
but then what? 
 I have lost the action/event etc I was working on

**To Reproduce and suggestions for addressing this at the end of the video: 
basically, NOT invite to upload for a specific community, or if so, open that in a new tab (but questions about interaction with the action-creation tab)
see video: 

https://user-images.githubusercontent.com/30277868/199554186-7f405e6a-15d1-4911-9fd6-a81c2efd2475.mp4

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kaatvds** [comment]
other issue flagged: in drop down box when selecting a comm to upload to, list should be alphabetical

**Comment by frimpongopoku** [comment]
@kaatvds this video demo is SUPER useful. Will be working on this issue. 

It was also very insightful to see you  use the features and get absolutely confused, even though I thought the structure couldn't be any more straightforward 🤣 🤣 🤣. 


I could make the form temporarily keep user content even when they havent submitted, until they explicitly press "cancel"(Will clear their form)  or "submit"(Which will do the usual) on the form. 

This way a user can move around  freely(like you did), and still not lose their content.

**Comment by Davidjwkinghorn** [comment]
It would be great to have form content preserved. I suggest we open the gallery in a new tab when a user clicks "Upload an image for specific communities instead". Down the road we could lose that link altogether and provide all the features from that form (only add image to X community, description, tags, etc) on the media library modal within the action, event, etc form.
