### ISSUE TITLE
global actions duplicate

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#80]
ISSUE 1233
Reported on Mon Jan 06 2020 15:47:54 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = High
STATUS =  - Submitted 

Site Url: http://admin.massenergize.org/admin/read/actions

Description:
Everytime I duplicate a Global action and change/edit it to assign it to a specific community, it creates the one in that community but ALSO duplicates/retains it as a global copy. Hence there are now 5 or so global "Buy an EV" actions.

User Role: Community Admin

**Comment by kaatvds** [comment]
clsoed because same as $94
