### ISSUE TITLE
Signing into Admin portal, it takes me to the Share Event View screen always

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#803]
**Describe the bug**
When I sign in as a cadmin or sadmin it takes me to a screen I was at in a previous session.  Not the one I was at most recenly but a recent one that the browser remembers.  Not what I want in general.  Generally unless I enter the admin portal from a link it should take me to my dashboard.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BradHN1** [comment]
@frimpongopoku - this bug is really annoying and I think should be easy for you to fix.

**Comment by BradHN1** [comment]
Encountered a crash on dev when I signed in and clicked the link to take me back to where I was.  Here is javascriopt console:
![Screen Shot 2023-02-25 at 11 45 28 AM](https://user-images.githubusercontent.com/12800484/221369165-9c4791ba-4ade-4a20-a206-1506df7954a1.png)

**Comment by BradHN1** [comment]
Sentry shows me this crash occurs in helper function `getAdminApiEndpoint` line:
  const isSuperAdmin = auth.is_super_admin;

presumably because auth wasn't (yet) defined.
It was trying to list communities since I was on the All Communities page.
Apparently the render method was called before the auth had been passed in.

**Comment by abdullai-t** [comment]
> Sentry shows me this crash occurs in helper function `getAdminApiEndpoint` line: const isSuperAdmin = auth.is_super_admin;
> 
> presumably because auth wasn't (yet) defined. It was trying to list communities since I was on the All Communities page. Apparently the render method was called before the auth had been passed in.

@BradHN1, I have made a [PR](https://github.com/massenergize/frontend-admin/pull/859) on nit
