### ISSUE TITLE
Simplify uploading of picture from your laptop.

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#805]
**User Story.**
Users (community admins or regular users) need to be able to upload an image easily without a lot of steps.  
Here is the process now:

You add to the gallery by uploading a picture when creating or editing an action, event or other thing, instead of through the “Media Gallery” which used to be there.  When you choose “Select an Image”, then usually “Upload” at the top (unless you want to select a picture from the gallery).  Then you can choose “browse” if you want to upload a picture from your laptop, then hit the “Upload” button, and then choose “Insert” once it is uploaded.  

That is 5 steps.  I think this can be done in 4 steps and give the opportunity for the user to provide information for the library.

Choose "Insert an image", then upload should be the default, browse for an image and choose "Select", and then the image is automatically uploaded and the image shows in a dialog where user can fill in details (name, source, tag) and then "Insert" (or cancel).

**Additional details/context**
Add any other details, context, UI mockups, examples from other products, or anything else that might help the developers know what to make.

**Value added.**
What do you think the value of adding this feature is? Help managers and developers know how this should be prioritized.

**Acceptance criteria.**
The conditions that must be met for this to be done. For example, for a login feature: User is securely and reliably logged in until timeout or manual sign-out.

**Comment by kaatvds** [comment]
needs more speccing in concert with the rest of the media gallery. Assigning to myself to work on in April.
