### ISSUE TITLE
Unsharing events on "giving" community end

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#814]
As a CAdmin
how could I change my mind about an event that I had agreed to share with other communities? Now I don't want it shared - what happens?

**Comment by kaatvds** [comment]
I think this is easy: you go to the event and select "I don't want to share" . 
Question: does this then yank the event off the sites of the communities that had shared it?

**Comment by frimpongopoku** [comment]
@kaatvds  how would you want it to be? We could yank it from there if thats what you want.

**Comment by frimpongopoku** [comment]
@kaatvds, I just went to investigate. In the codebase, we already yank it 🤣 🤣  so yeah (Its live already). You could test it out too when you have time just to be sure 🤝 .
