### ISSUE TITLE
Approved testimonial not saving as approved

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-admin#821]
A user submitted a testimonial. It is marked unapproved in the list of testimonials for Energize Framingham. Upon opening the testimonial, I am able to click approve "yes" and go live "yes." However, when I click Save, there is no response. It does not save, the screen does not change and there is no error message.
<img width="157" alt="image" src="https://user-images.githubusercontent.com/60662056/213460286-dc71a817-fc4a-4fdb-84a8-f9168b754bbc.png">

**Comment by apowelka** [comment]
<img width="412" alt="image" src="https://user-images.githubusercontent.com/60662056/213551406-4dbd2e3a-d84e-494d-9fd1-37b4e9e77be5.png">

**Comment by BradHN1** [comment]
The reason it didn't work is that the rank field wasn't filled in:


![Image](https://user-images.githubusercontent.com/12800484/218581336-d18b071e-cff4-4724-9126-97b74ad07e18.png)

I will fix that so it doesn't happen again.  For now, please set the rank and category.
