### ISSUE TITLE
Event sharing: still lists events that are past the event date; pls also add dates to list

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-admin#822]
On this page https://admin.massenergize.org/admin/edit/7/home

![image](https://user-images.githubusercontent.com/60662056/214155565-c6781a78-c167-4c24-9e17-a69eab626c24.png)

As a CAdmin, I want to be able to quickly choose the events that I wish to display on my home page. Right now, the options list has a bug in that events that have already gone by are still listed in the share list. These should not be visible. 

It will also be very helpful to:
a) add a date to the event at the start
b) sort the events by date

**Comment by BradHN1** [comment]
I think Aimee suggested the date at the beginning of the string. 
Question for @kaatvds and @apowelka : 
1.  on the home page featured event selection, do we want to not show events whose end-date (or start-date) is in the past?
2. if an event end-date is in the past, do we want it to disappear automatically on the community portal?

**Comment by BradHN1** [comment]
Currently with this change, the events selection list includes past events, but missing a couple of the events that had been selected so I can't unselect them:
<img width="1050" alt="Screen Shot 2023-02-10 at 2 09 39 PM" src="https://user-images.githubusercontent.com/12800484/218177604-4d54f795-b089-4f34-b335-a719d495dfd3.png">

**Comment by apowelka** [comment]
Add date as first item in list of events that are able to be shared and sorted by date.
Events with past end dates should not be shared.

on the home page featured event selection, do we want to not show events whose end-date (or start-date) is in the past? - **correct, do not show**

if an event end-date is in the past, do we want it to disappear automatically on the community portal? - **what do you mean? doesn't it move the the "past" tab?**

**Comment by emmawuerth** [comment]
@BradHN1 I'll work on addressing that right now -- I see what I overlooked on the past events front and will look into the selection problems. @apowelka To clarify, the checkbox will exclude all past events, and it will be sorted chronologically so that the soonest event in the future is at the top, while events further in the future are down lower. Is that correct?

**Comment by BradHN1** [comment]
@apowelka I was referring to the home page, which doesn't have tabs.
