### ISSUE TITLE
sharing new Actions with all from Template (Global)

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#83]
ISSUE 1238
Reported on Mon Jan 06 2020 18:21:55 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = Medium-High
STATUS =  - Submitted 

Site Url: http://admin.massenergize.org/admin/read/actions

Description:
Once communities are off and running, let's say Energize Wayland  creates a new template action, it would be great to have it prompt "do you want to copy this into all existing communities Actions lists, in an unlive format. "

User Role: Super Admin

**Comment by kaatvds** [comment]
basically this means "would you like to make this a Template action?"  (visible to all Cadmins)
Ideally when they happens it goes first to the MassEn content manager who vets it and then if it is good makes it into a template.
