### ISSUE TITLE
Download Users crashes admin portal on dev

### ISSUE THREAD

**Issue by emmawuerth** [massenergize/frontend-admin#834]
**Describe the bug**
As super admin tried to download the Users CSV and got a blank white screen.

**Smartphone (please complete the following information):**
<img width="975" alt="Screen Shot 2023-02-08 at 10 21 44 AM" src="https://user-images.githubusercontent.com/60861673/217618290-a43c9fa4-6cf5-4189-9354-74fab816ed1a.png">

**Comment by abdullai-t** [comment]
I think this might have been fixed. I just tested it in prod and it worked. Can you try again?

**Comment by emmawuerth** [comment]
I'm receiving an email with the data, but the screen still is blank. Is there anything else that I can try?

**Comment by abdullai-t** [comment]
will take a look
