### ISSUE TITLE
Community Engagement display - requested changes

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#857]
The Community Engagement section is a big improvement.  Here is what it looks like now:
<img width="1006" alt="Screen Shot 2023-02-24 at 9 21 48 AM" src="https://user-images.githubusercontent.com/12800484/221203678-87c9436d-425f-4a50-95ee-6447d45a8880.png">

When editing the date, this is the current dialog:
<img width="961" alt="Screen Shot 2023-02-24 at 9 31 34 AM" src="https://user-images.githubusercontent.com/12800484/221203994-ea9366d2-d8a7-4594-87f5-068f59080969.png">

We would like the following changes:
1. Add the community name right next to the title "Community Engagement".  Put the date field at the top right corner of the box.
2. If the cadmin has more than one community, have a pull-down to select which community is showing, and make it clearly readable.
3. If the custom date is selected, show that date in the top right of the box.  Perhaps when you click on the date, the field changes to the pull down to select the date.  If another choice is selected, like Last Week, show it as "Last Week (Jan 23-Feb 1)" so the date range is showing.
4. In the dialog to select a custom date, Apply should hide the dialog, and cancel should do the same without setting a date.
5. Eliminate the link "Click for more specific results"
6. If a category (like Actions Completed) has 0, eliminate the link "See involved actions"
7. "See Involved Testimonials" links to a list of actions.  It should show the list of submitted testimonials.
8. Eliminate the title "IMPACT", and change the link to "View the impact page for (community)"

**Comment by frimpongopoku** [comment]
oooo I didnt see this ticket 💀
