### ISSUE TITLE
can't zero n "attained no of actions" and "how many households joined" in Home page

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#86]
ISSUE 1251
Reported on Thu Jan 09 2020 14:09:46 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = 
STATUS =  - Submitted 

Site Url: http://admin.massenergize.org/admin/edit/3/home

Description:
I can't seem to zero the "attained no of actions" and "how many households joined" in Home page. It says submitted but then it refills the numbers and they keep showing up on donut on home page - which is fine if it repoplates with organic data....

User Role: Community Admin
Notes: ????

**Comment by ellentohn** [comment]
I put to 0 the attained actions and 0 for attained households on the home page. It accepted this change. But when I checked the Dev site for Wayland it showed the old #s and when I refreshed the https://admin-dev.massenergize.org/admin/edit/80/home - it showed the old #s I had in for Wayland which were 862 for actions and 448 for households

**Comment by ellentohn** [comment]
I think this is a bug when using a 0 -- when I set it to 1 for households and 1 for actions it retains the 1 and 1. But then also continues to add in the self reported actions and households which we do not want  to happen. @brad says there is a separate ticket API #82

**Comment by kaatvds** [comment]
on cadmin homepage I entered 300 in "manual input". On donuts it now only shows 300. the "organic" actions are not counted. I added and removed action in my "copmleted" list in my profile and it has no effect on the 300.

**Comment by BradHN1** [comment]
@kaatvds @Opoku-Agyemang @Pongo1 
This has been fixed in the donut-fixes branch to frontend-portal.
