### ISSUE TITLE
Multiple bugs on Cadmin's About Us page

### ISSUE THREAD

**Issue by emmawuerth** [massenergize/frontend-admin#878]
On the About Us Page where cadmins edit their community pages, there are multiple bugs. First, adding a video link just shows up as blank space on the community portal. Second, trying to upload an image makes the whole screen go blank. Last, disabling the page does not work (still shows up on the community portal). 

**To Reproduce**
1. Go to the About Us Page under Pages on the community Profile and test these features. 

**Desktop:**
 Mac, Chrome

**Comment by BradHN1** [comment]
Fixed the second bug : blank page while trying to upload an image:

nextProps not defined in CropModal.js

Other two bugs I can't reproduce:
add video link: check out community-canary.massenergize.org/ChelmsfordMA/aboutus?sandbox=true

disabled page, and the "Our Story" disappears from the About Us menu

**Comment by emmawuerth** [comment]
Just retested: blank page fixed, white space from video link only happens when the link is invalid (not sure if that's the desired behavior), and disabling the page removes it from the About Us menu, but is still accessible via the "Learn/Join" icon on the home page (also don't know if this is the desired behavior).
