### ISSUE TITLE
Edit Action - Live button not working

### ISSUE THREAD

**Issue by emmawuerth** [massenergize/frontend-admin#885]
**Describe the bug**
Clicking Yes/No under "Live?" in the list of all actions does not seem to work/update on the community portal site.

**Comment by emmawuerth** [comment]
same thing with teams and events! can see all the events/teams/actions on the community portal even if they are marked "no" under "Live?"

**Comment by BradHN1** [comment]
THe issue was the sandbox which was why non-live content was showing up
