### ISSUE TITLE
possibility to un/live events (so we can keep them)

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#90]
ISSUE 1257
Reported on Wed Jan 15 2020 17:16:57 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = 
STATUS =  - Submitted 

Site Url: http://admin.massenergize.org/admin/read/events

Description:
Would it be possible to unlive events after they're  over (also, later, automate that when they have passed)? That way we can keep them stored and can edit them and revive them. Lots of event recur so this way we wouldn't have to recreate them anew each time.

User Role: Community Admin

**Comment by kaatvds** [comment]
sorry have to reopen it. NOT live events still show on the events page... E.g. "Massachusetts Climate Legislation-Copy-279"
![image](https://user-images.githubusercontent.com/30277868/76807633-63417180-67bb-11ea-88be-8586b9e93301.png)
![image](https://user-images.githubusercontent.com/30277868/76807645-6b99ac80-67bb-11ea-8de5-dd642a171b8f.png)
