### ISSUE TITLE
filter settings in lists are retained too strictly and are reset without my prompting

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#900]
As a superadmin I go to all actions: it lands me on Energize Newburyport because that was my last search. I reset the filter to EnergizeWayland (recording starts with that). I click to unlive an action. Unnoticed, (almost) when I clicked on "unlive," the list has changed back to EnergizeNewburyport. This happens each time I switch back to Wayland.  (It does unlive the correct action)
This happens to non-super admins as well, that lists get reset to previous even after filters have been changed. Very confusing.

https://user-images.githubusercontent.com/30277868/226355288-a673ddee-2b9b-4463-b499-bcd11e493662.mp4

**Comment by abdullai-t** [comment]
@kaatvds, the pagination, filter and search I worked on fixes this issue but the code is only in dev and canary. Since @BradHN1 is not around to push the code to prod, I will make a quick fix for the issue until @BradHN1 pushes the code to prod

**Comment by BradHN1** [comment]
Verified fixed already in Canary
