### ISSUE TITLE
Event rank value plus enter causes media library to pop up

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-admin#904]
As a CAdmin, I am creating a new event. I enter a rank value and hit enter. The media library pops up.

![2023-03-27 07_59_07-MassEnergize - Event   Campaigns](https://user-images.githubusercontent.com/60662056/227935635-e6a96fc9-19ee-4bcb-956f-38ed29badb62.png)

desktop chrome

**Comment by abdullai-t** [comment]
This issue has already been fixed, but the code hasn't been deployed to prod yet.

**Comment by abdullai-t** [comment]
This issue has already been fixed, but the code hasn't been deployed to prod yet.
