### ISSUE TITLE
Community Engagement - unable to specify community properly

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#907]
**Describe the bug**
Testing in Canary with a profile which has several communities to admin:
<img width="841" alt="Screenshot 2023-04-06 at 12 47 59 PM" src="https://user-images.githubusercontent.com/12800484/230444377-9cc4b62c-73e8-4012-97db-0ba8c04837a5.png">

By default it always picks "Energize Falmouth" first, which is annoying.  It should perhaps use localStorage to remember what community I selected last.

I select "Click for more specific results", and select "Cooler Concord!".
<img width="850" alt="Screenshot 2023-04-06 at 12 51 08 PM" src="https://user-images.githubusercontent.com/12800484/230444674-4b3dbef5-0234-49cf-8357-3e8238e7096f.png">

When I apply, the title always says: Community Engagemnent A New Community.

I would like to have this form changed as I had requested, to not have "click for more specific results".  Make the Community Name which shows a link to selector box to select one community (not All).  It should be as simple as it is now to selet the date.

**Comment by BradHN1** [comment]
Nice work @frimpongopoku 

Cosmetic issue: the text in the community and time interval chips is small, and should be closer to the size in the "Community Engagement" title.  I suggest the title be changed to "Community Engagement Summary for "
If a community admin only has one community, that selector should just be replaced by the text of the community name, since there would be nothing to select.
Can you add a title "Time interval: " before the time interval? 

There is a bug in the data which is shown, as you can see in the video below.  I was testing using my coolerconcord@gmail.com admin account, and it first picks Maynard as a community and reports like 50 sign-ins,  Then when I change the community to a different one, and back, that number goes to zero sign-ins, which is I think correct.  

https://user-images.githubusercontent.com/12800484/230638345-b25689c0-7348-4ceb-aa56-f13da454cb3f.mov

The initial API call summary.get.engagements does not pass in a community id, that is probably the problem.
Args = {'time_range': 'last-month'}

When I select a community, it reloads using Args = {'time_range': 'last-month', 'communities': ['6']}

**Comment by frimpongopoku** [comment]
@BradHN1  when you are uploading, please make sure you check that the video is done uploading. Cos this one you were trying to show did not finish uploading before you published the comment. It needs to finish before you save your content.

**Comment by frimpongopoku** [comment]
@BradHN1, I would really like to see that video of what you explained earlier.... 
Cause when I checked on my end, everything seems fine. The initial request is run with "last-month" and  the first comunity in my list. And the data that comes up is appropriate 🤔 . So lets try the video again, maybe Im missing something... 🤔  

In other news I have added some of the light tweaks you requested for how the title should show when the cadmin has only one community, and also added the "time Interval" text.

**Comment by BradHN1** [comment]
Thanks @frimpongopoku - the video I tried to upload is fixed.  It just shows that in my case (testing in canary with 3 communities as admin) the data on the first fetch is incorrect.  Perhaps a timing issue: when I'm testing with canary, and `useEffect` is first called, the value of `first` wasn't filled yet so it loads the activity for all my communities instead of the one showing in the selector box.

I get what you mean about changing the look and feel of the MaterialUI Dropdown, let's not spend the time.

The one thing I think we should do to simplify that box is for now eliminate the last bit ("See impact of any your communities...") which is not so important and since it has a different community selector is a bit odd.
