### ISSUE TITLE
Change  WYSIWYG library or settings

### ISSUE THREAD

**Issue by Opoku-Agyemang** [massenergize/frontend-admin#92]

**Comment by kaatvds** [comment]
Am collecting several tickets under here. The new library should enable:

- bold, italic
- embedded links (that open in new tabs)
- bullets and numbering
- line break
- paragraph breaks (so an  empty line in between paragraphs)
- if possible, also different font sizes

the new library should not preclude the later possibility of putting pictures in the body of the text (with wrapping)
