### ISSUE TITLE
Admin list csv downloads have garbage in some columns (Is it Live)=[object Object]

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#938]
**Describe the bug**
A csv download of the All Communities page looks like this:
<img width="964" alt="Screenshot 2023-04-20 at 9 20 40 AM" src="https://user-images.githubusercontent.com/12800484/233379094-ee273d9e-2c61-4c8f-b3fb-805c66594fb2.png">

The column Is it Live? should be Yes or No, not [object Object]

**Comment by abdullai-t** [comment]
@BradHN1, the `live` property no longer exists in all communities CSV both in dev and prod

**Comment by BradHN1** [comment]
@abdullai-t - This download comes from the Communities list page, clicking the download icon.  The CSV file downloaded is called tableDownload, and it looks like this:


![Image](https://github.com/massenergize/frontend-admin/assets/12800484/076635f9-7d6a-46b1-b3f6-aa4f36aa9df6)

**Comment by frimpongopoku** [comment]
@abdullai-t  you worked on this last week right?

**Comment by abdullai-t** [comment]
I didn't commit the code

**Comment by abdullai-t** [comment]
This has been fix
