### ISSUE TITLE
TinyMCE control buttons missing on new version, and TinyCloud messages

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#941]
**Describe the bug**
Upon updating the version of the TinyMCE package, several of the control buttons disappeared: link, image, bullets, numbers, font and fontsize.

Try reverting to earlier version until it is fixed

Also, the "This domain is not registered with Tiny Cloud message came back, even though  the domain is registered.
<img width="866" alt="Screenshot 2023-04-21 at 1 43 05 PM" src="https://user-images.githubusercontent.com/12800484/233701046-9a5c1369-ebee-4b60-9d9e-8e6609915c45.png">

Try a fix suggested on StackOverflow to get that message to disappear:
https://stackoverflow.com/questions/50038470/tinymce-shows-error-in-the-editor

**Comment by frimpongopoku** [comment]
@BradHN1  you already implemented https://stackoverflow.com/questions/50038470/tinymce-shows-error-in-the-editor
right? Cos I can see it in code, and also I dont see it on my local, and deployed DEV
