### ISSUE TITLE
 Time To Introduce Sockets

### ISSUE THREAD

**Issue by frimpongopoku** [massenergize/frontend-admin#947]
So, in all of our applications both on Community and Admin Portals, the fundamental flow we always use is that: 
The frontend always hits a route, and the backend responds with something. The frontend is always the one that has the right to request, and there is no way for the backend to directly identify a particular client and keep communicating with them if anything. The communication is always one-directional. Now, even though this structure works for almost all of the scenarios we care about on all our portals, there a few scenarios where it is smarter, and a better use of our resources, if we use a different kind of communication with the backend -- and that is using Sockets. 

## SOCKETS (OVERSIMPLIFIED) 
Here is how sockets work. Just like every other thing, we just need to make a route that any of our frontend portals can hit. After the portal hits the route, there is a kind of a secure and unique two-way connection between the frontend and the backend, for the entire time that a user does not refresh their app( If they do refresh, its no problem, the route will be hit when the app is loading again, and the connection will be re-established...). Whats good about this particular two-way structure is that, depending on whatever functionality we implement it with, the backend will always be able to deliver messages to the frontend, without the frontend having to initiate a request first.

### Communicating Admin Auth State
This socket implementation perfectly fits into our need to better communicate user authentication state on the admin frontend portal (Recommended by @Opoku-Agyemang ). We could completely offload the authentication tracking we are using on the frontend to the backend (which is where it should be happening anyway). If we do this, the backend will be the one to tell the frontend portal as soon as it detects that the admin's 24hrs is up, or if they have just been idle for a while. 

There will be no need for time tracking on the frontend, and no need to periodically hit "/whoami" to check the status of the admin. We would receive a notification immediately anything changes in the user's authentication state and we could show something similar to this(like what we experience on AWS):
![Screenshot 2023-04-27 at 08 00 08](https://user-images.githubusercontent.com/26961591/234756199-7ce1e97e-777e-44d7-b583-b50e75020599.png)

### Frontend Portal Teams
Secondly, I think  I remember in one of our meetings @BradHN1  mentioned that the core team was planning a more exciting teams page that might involve messaging on the community portal between teams and team members...?  Yes, this is the perfect ground work to lay for anything that involves real-time messaging on any of our platforms. So this plays well into our future too.

## HOW LONG WILL THIS TAKE TO IMPLEMENT? 
It should not take more than a week. And in the worst case, it could be done within our two-week sprint.

## EXPECTED BACKEND CHANGES 
- [X] No DB changes needed
- [X] None of the old routes will change 
- [X] New socket routes will be introduced 
- [X] Our django app will just be switched from `wsgi` to an `asgi` app.
- [X] Install `channels` and thats pretty much it.

**Comment by BradHN1** [comment]
Awaiting AWS changes and evaluation of channel disconnects
