### ISSUE TITLE
Add functionality to list users who have marked actions as done or to-do

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#951]
Community admins or super admins need an easy way to list the users who have marked actions as done or todo.
It should work just like listing members of a team, with a "Users list" column in the list view with the people icon:
![Screenshot 2023-05-01 at 11 48 45 AM](https://user-images.githubusercontent.com/12800484/235481658-dd150aec-dec1-414f-b14a-bc8eda7b51aa.png)

and in the Edit for a link under the text "Want to see a list of users who have taken this action or marked as ToDo?"

A separate API ticket creates a route actions.users.list to provide this information

Separately:to free up some space, I would suggest we remove the Tags from the actions list.  Otherwise, we should list all the tags, not just the first few and "..." which is not so useful.  It can overflow onto as many lines as needed.

![Screenshot 2023-05-01 at 11 23 59 AM](https://user-images.githubusercontent.com/12800484/235477226-4a9afeab-7d57-40d4-adfa-7f99eeadf868.png)

**Comment by apowelka** [comment]
these are the fields that should be downloaded:
First Name
Last Name
Preferred Name
Email
Status (a field that displays Done or to-do)
Testimonial (yes/no)
User Role

**Comment by abdullai-t** [comment]
@BradHN1 , @kaatvds  @apowelka
Here is a demo of the UI based on the description above. I haven't added the part where the admin can request a CSV.
https://github.com/massenergize/frontend-admin/assets/42780120/9f7f1996-f3ea-481f-a4b2-3561c765cd20
