### ISSUE TITLE
Inconsistent data in some filtered Admin Portal lists

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#963]
**Describe the bug**
In Dev admin portal (same for prod I think), I click on user engagement to list users, and I get the following view:
<img width="1406" alt="Screenshot 2023-05-12 at 10 59 34 AM" src="https://github.com/massenergize/frontend-admin/assets/12800484/22ce6fc3-dd49-4469-ae61-bb9e499ab615">

You can see it is filtering on 4 users, but three are duplicated so there should be linly the 4 entries, not 7
At bottom of the list it says "1-12 of 12" which isn't correct either

**Comment by frimpongopoku** [comment]
This is fixed here https://github.com/massenergize/frontend-admin/pull/977
