### ISSUE TITLE
cadmin dashboard: weird lists in "What to do Next" lists

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#966]
When I click on any option in What to do next I get a bunch of "buttons" first. This can be a long list. Why are they there?  What happens if I x one out? They seem to have no function and if they do it's not apparent.
Can we do away with these, or hide them if they're necessary?

<img width="1257" alt="Screenshot 2023-05-17 at 2 26 16 PM" src="https://github.com/massenergize/frontend-admin/assets/30277868/be77386d-5c80-4ee3-b277-2eb022e93809">

**Comment by kaatvds** [comment]
same under options in Engagement summary: hide the grey 'buttons"

**Comment by frimpongopoku** [comment]
@kaatvds  the chips are an indication of what filters have currently been applied on the table. But yes I see how that is a bad look and can be confusing. I will look into disabling it when there is a lot of them.

**Comment by kaatvds** [comment]
I tihnk it would be great to remove them for all, even if there are only a couple. It has no functionality for the Admin and is confusing for them: what do  these mean, what do I do with these, what happens if I x them out... WE know this is the filter, but for them it's not clear.

**Comment by frimpongopoku** [comment]
They do actually have a functionality. Clicking on the "X" is a quick way  let you remove a selected filter. So lets say you have added a "Wayland" and "42"  as filters on the table, clicking on the "X" on "Wayland" will remove the wayland filter from the table, to make it only show items that are related to "42". But I hear you, its not obvious enough, and we have not communicated it properly. So I will try and disable it completely for now.

**Comment by kaatvds** [comment]
That is their function, but the relevant question is: why would any cadmin use that function, x out a number in their filter on these pages? They would have to go look at what those numbers refer to, etc.
