### ISSUE TITLE
Superadmins can't share events with communities

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#983]
**Describe the bug**
As a superadmin I should be able to share an event from any community with any other, in order to help the receiving community.  But when I try it says "No communities on this list".  See the picture:
![Screenshot 2023-05-27 at 7 06 15 AM](https://github.com/massenergize/frontend-admin/assets/12800484/742e70d3-ac12-4a1a-b66f-77a96fa1abfe)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abdullai-t** [comment]
@BradHN1, there is a PR on this. here is the [link](https://github.com/massenergize/frontend-admin/pull/1020)
