### ISSUE TITLE
All Events (once live option is open): add live Y/N filter column 

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#99]
For All Events Headers/Columns
Once live option is open (cf. issue #90), add: Live (Y/N) in column to the right on All events page.

**Comment by ellentohn** [comment]
Can we add Yes to this filter,  For live as both a Cadmin and Sadmin it allows us to filter for (All/No). Can we get (All/Yes/No) so that we can see only the live event?
