### ISSUE TITLE
CAN: confused as to when an event (and edit button) show up on usr portal

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#992]
As a cadmin I have

event 100 = not live - On User portal I can EDIT this (with edit button over the orange background of the RSVP button: looks haphazzerdly placed??)
<img width="360" alt="Screenshot 2023-06-02 at 3 47 39 PM" src="https://github.com/massenergize/frontend-admin/assets/30277868/605b7ac6-d7c7-4781-8351-7e3c6fdcc71d">

event 100-copy:  also not live  but DOESN't show up the user portal - why? I don't see a difference...

<img width="470" alt="Screenshot 2023-06-02 at 3 45 16 PM" src="https://github.com/massenergize/frontend-admin/assets/30277868/5f57ad98-7f1d-404c-9e34-30171c039648">

<img width="1443" alt="Screenshot 2023-06-02 at 3 44 56 PM" src="https://github.com/massenergize/frontend-admin/assets/30277868/bcb4c990-49ac-49ce-9d67-6f56fef8c298">

**Comment by kaatvds** [comment]
then i made event 100 LIVE 
> now Event 100-copy gets the "edit" button
can one only edit one at a time? Should ALL events be editable from the user portal?

**Comment by kaatvds** [comment]
Shouldn't all the events I created - live or not - be editable from the user portal?

**Comment by abdullai-t** [comment]
@kaatvds, Events that are not live are only visible on the community portal to the account(email) that created them. Please check to see if the email you used to create the copied event on the admin portal is the same as the email you used to log in to the user portal.

**Comment by kaatvds** [comment]
it is possible that I created one as a superadmin (unawares as it kept reverting me without my knowledge) and the other as a cadmin but unfortunately I can't figure out who created event 313 (event100-copy) : I can't find a record of its creation in the dashboards (either as cadmin of as sadmin)

**Comment by kaatvds** [comment]
also, shouldn't ALL the events I created - live or not - be editable from the user portal?

**Comment by abdullai-t** [comment]
Yes. But once it is published, it is no more editable on the user portal

**Comment by kaatvds** [comment]
I see, like Testimonials: editable by user until admin publishes it (=makes it live). In the above example both event 100 (311) and event100-copy (313) are not live, and I believe both were. I someone can find out who  (ti was me, but in what persona) created event 313 we can see what the problem is.  If I have time I'll try to recreate the bug later today.

**Comment by BradHN1** [comment]
For future: We’ll need to think about how to make submitted content still editable after making live.  Edits would need to be approved by a cadmin (unless the cadmin profile makes the edit), and approving should be low barrier (via the notification, not needing to go to admin profile.  Fairly big project for later this summer
